<?php

$query_array=array("headline"=>array("name"=>__("Hotfixes & Patches"),
                                     "sql"=>"SELECT `system_name` FROM `system` WHERE `system_uuid` = '" . $_REQUEST["pc"] . "'",
                                     ),
                   "sql"=>"SELECT software_name, software_version, software_publisher, software_url FROM software, system WHERE software_uuid = '".$_REQUEST["pc"]."' AND (software_name LIKE '%hotfix%' OR software_name LIKE '%Service Pack%' OR software_name REGEXP '[KB|Q][0-9]{6,}') AND software_uuid = system_uuid AND software_timestamp = system_timestamp ",
                   "sort"=>"software_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>__("Computers installed this Software"),
                                "var"=>array("view"=>"systems_for_software",
                                             "name"=>"%software_name",
                                             "headline_addition"=>"%software_name",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"software_name",
                                               "head"=>__("Software Name"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "20"=>array("name"=>"software_version",
                                               "head"=>__("Version"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"list.php",
                                                            "title"=>__("Computers installed this Version of this Software"),
                                                            "var"=>array("view"=>"systems_for_software_version",
                                                                         "name"=>"%software_name",
                                                                         "version"=>"%software_version",
                                                                         "headline_addition"=>"%software_name",
                                                                        ),
                                                           ),
                                              ),

                                   "30"=>array("name"=>"software_publisher",
                                               "head"=>__("Publisher"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"%software_url",
                                                            "title"=>"External Link",
                                                            "target"=>"_BLANK",
                                                           ),
                                              ),
                                  ),
                  );
?>
