<?php

$query_array=array("headline"=>__("List All Modems"),
                   "sql"=>"SELECT * FROM modem, system WHERE modem_uuid = system_uuid AND modem_timestamp = system_timestamp ",
                   "sort"=>"system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"net_ip_address",
                                               "head"=>__("IP"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                    "40"=>array("name"=>"net_user_name",
                                               "head"=>__("Network User"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "50"=>array("name"=>"modem_description",
                                               "head"=>__("Modem"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "60"=>array("name"=>"modem_device_type",
                                               "head"=>__("Type"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "70"=>array("name"=>"modem_attached_to",
                                               "head"=>__("Attached to"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "80"=>array("name"=>"modem_device_id",
                                               "head"=>__("Device ID"),
                                               "show"=>"n",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
