<?php
if(!isset($_GET["type"])) $_GET["type"]="%";
if(!isset($_GET["name"])) $_GET["name"]="%";

$query_array=array("headline"=>__("List Keys for Software"),
                   "sql"=>"SELECT ms_keys_name, ms_keys_cd_key, system_name, net_ip_address, net_user_name, system_uuid FROM ms_keys, system WHERE ms_keys_key_type LIKE '".urldecode($_GET["type"])."%' AND ms_keys_name LIKE '".urldecode($_GET["name"])."%' AND ms_keys_uuid = system_uuid AND ms_keys_timestamp = system_timestamp ",
                   "sort"=>"system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"net_ip_address",
                                               "head"=>__("IP"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "40"=>array("name"=>"ms_keys_name",
                                               "head"=>__("Software"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"ms_keys_cd_key",
                                               "head"=>__("Key"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                     "60"=>array("name"=>"net_user_name",
                                               "head"=>__("Network User"),
                                               "show"=>"y",
                                               "link"=>"y",
                                             ),
                                 ),
                );
?>
