<?php

$query_array=array("headline"=>__("Delete Other Equipment"),
                   "sql"=>"SELECT other_id, other_ip_address, other_network_name, other_type, other_description, other_linked_pc FROM other WHERE other_ip_address <> ' Not-Networked'",
                   "sort"=>"other_ip_address",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("other"=>"%other_id",
                                             "view"=>"other_system",
                                            ),
                               ),
                   "fields"=>array(
                                   "10"=>array("name"=>"delete",
                                               "head"=>__("Delete"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "sort"=>"n",
                                               "search"=>"n",
                                               "get"=>array("file"=>"delete_other.php",
                                                            "title"=>__("Delete Other Equipment"),
                                                            "onClick"=>"return confirm('".__("Do you really want to DELETE this item?")."');",
                                                            "var"=>array("other"=>"%other_id",
                                                                        ),
                                                           ),
                                              ),
                                   "20"=>array("name"=>"other_ip_address",
                                               "head"=>__("IP"),
                                               "width"=>"160",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"other_network_name",
                                               "head"=>__("Attached Device"),
                                               "width"=>"160",
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"system.php",
                                                            "title"=>"Go to System",
                                                            "var"=>array("pc"=>"%other_linked_pc",
                                                                         "view"=>"summary",
                                                                        ),
                                                           ),
                                              ),
                                   "40"=>array("name"=>"other_type",
                                               "head"=>__("Type"),
                                               "align"=>"center",
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"other_description",
                                               "head"=>__("Description"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                  ),
                  );
?>
