<?php

$query_array=array("headline"=>__("List all Software Patches, Updates, Languagepacks, SPs with Hosts"),
                   "sql"=>"SELECT software_name, software_version, software_publisher, software_first_timestamp, software_install_date, system_name, net_user_name, system_uuid FROM software, system where (software_name LIKE '%hotfix%' OR software_name LIKE '%Service Pack%' OR software_name LIKE '%Update %' or software_name LIKE '%MUI (%' or software_name LIKE '%Proofing %' or software_name LIKE '%Language%' or software_name LIKE '%Korrektur%' or software_name LIKE '%linguisti%' OR software_name REGEXP 'SP[1-4]{1,}' OR software_name REGEXP '[KB|Q][0-9]{6,}') AND software_uuid = system_uuid AND software_timestamp = system_timestamp ",
                   "sort"=>"software_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>__("Systems installed this Version of this Patches, Language Packs and Hosts"),
                                "var"=>array("name"=>"%software_name",
                                             "version"=>"%software_version",
                                             "view"=>"systems_for_software_version",
                                             "headline_addition"=>"%software_name",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"software_name",
                                               "head"=>__("Name"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"list.php",
                                                            "title"=>__("Systems installed this Software"),
                                                            "var"=>array("name"=>"%software_name",
                                                                         "view"=>"systems_for_software",
                                                                         "headline_addition"=>"%software_name",
                                                                        ),
                                                           ),
                                              ),
                                   "30"=>array("name"=>"software_version",
                                               "head"=>__("Version"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "40"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"system.php",
                                                            "title"=>__("Go to System"),
                                                            "var"=>array("pc"=>"%system_uuid",
                                                                         "view"=>"summary",
                                                                        ),
                                                           ),
                                              ),
                                    "50"=>array("name"=>"net_user_name",
                                               "head"=>__("Network User"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
											  											  
								  "52"=>array("name"=>"software_install_date",
                                               "head"=>__("First installed"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
											  

								  "60"=>array("name"=>"software_first_timestamp",
                                               "head"=>__("Audited"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),

                                  ),
                  );
?>
