<?php

    $query_array=array("headline"=>__("List other hosts running Nmap discovered service '".$_REQUEST["headline_addition2"]."' (version '".$_REQUEST["headline_addition3"]."') on ".strtoupper($_REQUEST["headline_addition1"])." port"),
                       "sql"=>"SELECT other_id, other_ip_address, other_network_name, other_description, other_type
                                      FROM other, nmap_ports
                                      WHERE nmap_port_number = '".$_REQUEST["name"]."' AND nmap_port_proto = '".$_REQUEST["headline_addition1"]."' AND nmap_port_version = '".$_REQUEST["headline_addition3"]."' AND (nmap_other_id = other_mac_address OR nmap_other_id = other_id)",
                       "sort"=>"other_network_name",
                       "dir"=>"ASC",
                       "get"=>array("file"=>"system.php",
                                    "title"=>"Go to other system",
                                    "var"=>array("other"=>"%other_id",
                                                 "view"=>"other_system",
                                                ),
                                   ),
                       "fields"=>array("10"=>array("name"=>"other_id",
                                                   "head"=>__("UUID"),
                                                   "show"=>"n",
                                                  ),
                                       "20"=>array("name"=>"other_ip_address",
                                                   "head"=>__("IP address"),
                                                   "show"=>"y",
                                                   "link"=>"y",
                                                  ),
                                       "30"=>array("name"=>"other_network_name",
                                                   "head"=>__("Hostname"),
                                                   "show"=>"y",
                                                   "link"=>"y",
                                                  ),
                                       "40"=>array("name"=>"other_description",
                                                   "head"=>__("Description"),
                                                   "show"=>"y",
                                                   "link"=>"n",
                                                  ),
                                       "50"=>array("name"=>"other_type",
                                                   "head"=>__("Type"),
                                                   "show"=>"y",
                                                   "link"=>"n",
                                                  ),                                             
                                      ),
                      );
?>