<?php

$query_array=array("headline"=>__("List all Keys"),
                   "sql"=>"SELECT system_uuid, ms_keys_name, ms_keys_cd_key, system_name, net_ip_address FROM ms_keys, system WHERE ms_keys_uuid = system_uuid AND ms_keys_uuid = system_uuid AND ms_keys_timestamp = system_timestamp ",
                   "sort"=>"system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"net_ip_address",
                                               "head"=>__("IP"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "40"=>array("name"=>"ms_keys_name",
                                               "head"=>__("Software"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"list.php",
                                                            "title"=>__("Keys for this Software"),
                                                            "var"=>array("view"=>"keys_for_software",
                                                                         "name"=>"%ms_keys_name",
                                                                         "headline_addition"=>"%ms_keys_name",
                                                                        ),
                                                           ),
                                              ),
                                   "50"=>array("name"=>"ms_keys_cd_key",
                                               "head"=>__("Key"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
