<?php
/**********************************************************************************************************
Module:	system_viewdef_report_full.php

Description:
	
		
Change Log:
	[Edoardo]		30/01/2008	Added Scheduled tasks, Env. variables, IP routes, Event logs, Pagefile, Mobo and Onboard devices sections.
								Added System last boot in the OS section and HDD status in the Fixed Disks section.
								Fixed System Software query to add MDAC/WDAC
	[Edoardo]		13/04/2008	Added the Automatic Updating Client Settings section and many IIS items
	[Edoardo]		19/05/2008	Added Driver provider, version and date in the Network card section
	[Edoardo]		23/05/2008	Modified Groups layout to horizontal
	[Edoardo]		04/06/2008	Added Index and Socket Type in the Processor section
	[Edoardo]		06/06/2008	Added CPU Sockets # and Memory Slots # in the Mobo section
								Added persistently Mapped drives and fixed Shared folders tags	
	[Edoardo]		23/07/2008	Added Slot # to the Memory section
	[Edoardo]		24/11/2008	Fixed Symantec client security detection for servers on the Security system viewdef - Other antivirus section
	[Edoardo]		04/03/2009	Sorted partitions list (by partition ID and drive letter)
	[Edoardo]		25/03/2009	Fixed query in the Software section to exclude the word 'Update' in software_name (like Java(TM) 6 Update X, LiveUpdate (Symantec Corp.), MS Windows Server Update Services and so on)
	[Edoardo]		21/05/2009	Added Printer share name to the Printer section
	[Edoardo]		01/08/2009	Added Logon As to the Services section
	[Edoardo]		28/05/2010	Added S.M.A.R.T. Failure Predicted to the Fixed Disks section
	[Edoardo]		31/05/2010	(suggested by jpa) Added Driver Name to the Printer section
	[Edoardo]		27/07/2010	Added OS Arch. to the OS section
	[Edoardo]		10/08/2010	Removed Printer section horizontal layout to fix pdf files creation
	[Edoardo]		26/08/2010	Fixed users/groups labels (users/groups description to be fixed)

**********************************************************************************************************/
$query_array=array("name"=>array("name"=>__("Report"),
                                 "sql"=>"SELECT `system_name` FROM `system` WHERE `system_uuid` = '" . $_GET["pc"] . "'",
                                ),
                   "views"=>array("system"=>array(
                                                    "headline"=>__("System"),
                                                    "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $pc . "' OR system_name = '" . $pc . "' ",
                                                    "fields"=>array("10"=>array("name"=>"net_uuid",
                                                                                "show"=>"n",
                                                                               ),
                                                                    "20"=>array("name"=>"system_name", "head"=>__("System Name"),),
                                                                    "30"=>array("name"=>"system_description", "head"=>__("Description"),),
                                                                    "40"=>array("name"=>"net_domain", "head"=>__("Domain"),),
                                                                    "50"=>array("name"=>"net_domain_role", "head"=>__("Domain Role"),),
                                                                    "60"=>array("name"=>"net_user_name", "head"=>__("Current User"),),
                                                                    "70"=>array("name"=>"system_first_timestamp", "head"=>__("Date First Audited"),),
                                                                    "80"=>array("name"=>"system_timestamp", "head"=>__("Date Last Audited"),),
                                                                    "90"=>array("name"=>"system_uuid", "head"=>__("UUID"),),
                                                                   ),
                                                    ),
                                  "manual"=>array(
                                                    "headline"=>__("Manual Data"),
                                                    "sql"=>"SELECT * FROM system_man WHERE system_man_uuid = '" . $pc . "' ",
                                                    "fields"=>array("10"=>array("name"=>"system_man_id",
                                                                                "show"=>"n",
                                                                               ),
                                                                    "20"=>array("name"=>"system_man_location", "head"=>__("Location"), "edit"=>"y",),
                                                                    "30"=>array("name"=>"system_man_date_of_purchase", "head"=>__("Date of Purchase"), "edit"=>"y",),
                                                                    "40"=>array("name"=>"system_man_value", "head"=>__("Dollar Value"), "edit"=>"y",),
                                                                    "50"=>array("name"=>"system_man_serial_number", "head"=>__("Asset Tag"), "edit"=>"y",),
                                                                    "60"=>array("name"=>"system_man_description", "head"=>__("Description"), "edit"=>"y","edit_type"=>"textarea",),
                                                                   ),
                                                ),
                                   "chassis"=>array(
                                                    "headline"=>__("Chassis"),
                                                    "sql"=>"SELECT system_vendor, system_model, system_id_number, system_system_type FROM system WHERE system_uuid = '" . $pc . "' AND  system_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "fields"=>array("10"=>array("name"=>"system_vendor", "head"=>__("Manufacturer"),),
                                                                    "20"=>array("name"=>"system_model", "head"=>__("Model #"),),
                                                                    "30"=>array("name"=>"system_id_number", "head"=>__("Serial #"),),
                                                                    "40"=>array("name"=>"system_system_type", "head"=>__("Chassis Type"),),
                                                                   ),
                                                    ),
                                   "motherboard"=>array(
                                                    "headline"=>__("Motherboard"),
                                                    "sql"=>"SELECT * FROM motherboard WHERE motherboard_uuid = '" . $_GET["pc"] . "' AND motherboard_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "fields"=>array("10"=>array("name"=>"motherboard_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "20"=>array("name"=>"motherboard_product", "head"=>__("Product"),),
                                                                    "30"=>array("name"=>"motherboard_cpu_sockets", "head"=>__("CPU Sockets"),),
                                                                    "40"=>array("name"=>"motherboard_memory_slots", "head"=>__("Memory Slots"),),
                                                                   ),
                                                    ),
                                   "onboard_device"=>array(
                                                    "headline"=>__("Onboard Devices"),
                                                    "sql"=>"SELECT * FROM onboard_device WHERE onboard_uuid = '" . $_GET["pc"] . "' AND onboard_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"onboard_description", "head"=>__("Description"),),
                                                                    "20"=>array("name"=>"onboard_type", "head"=>__("Type"),),
                                                                   ),
                                                    ),
                                  "hard_drive"=>array(
                                                    "headline"=>__("Fixed Disks"),
                                                    "sql"=>"SELECT hard_drive_index, hard_drive_manufacturer, hard_drive_interface_type, hard_drive_model, 
                                                                   hard_drive_partitions, hard_drive_size, hard_drive_scsi_bus, hard_drive_scsi_logical_unit, 
                                                                   hard_drive_scsi_port, hard_drive_status, hard_drive_predicted_failure
                                                            FROM hard_drive, system
                                                            WHERE hard_drive_uuid=system_uuid AND hard_drive_uuid = '" . $pc . "' AND hard_drive_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY hard_drive_index",
                                                    "fields"=>array("10"=>array("name"=>"hard_drive_index", "head"=>__("Index"),),
                                                                    "20"=>array("name"=>"hard_drive_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "30"=>array("name"=>"hard_drive_interface_type", "head"=>__("Type"),),
                                                                    "40"=>array("name"=>"hard_drive_model", "head"=>__("Model"),),
                                                                    "50"=>array("name"=>"hard_drive_partitions", "head"=>__("Partitions"),),
                                                                    "60"=>array("name"=>"hard_drive_size", "head"=>__("Size"),),
                                                                    "70"=>array("name"=>"hard_drive_scsi_bus", "head"=>__("SCSI Bus"),),
                                                                    "80"=>array("name"=>"hard_drive_scsi_logical_unit", "head"=>__("SCSI Logical Unit"),),
                                                                    "90"=>array("name"=>"hard_drive_scsi_port", "head"=>__("SCSI Port"),),
                                                                    "100"=>array("name"=>"hard_drive_status", "head"=>__("Status"),),
																	"110"=>array("name"=>"hard_drive_predicted_failure", "head"=>__("S.M.A.R.T. Failure Predicted"),),
                                                                    "120"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "partition"=>array(
                                                    "headline"=>__("Partitions"),
                                                    "sql"=>"SELECT * FROM `partition` WHERE (partition_uuid = '" . $pc . "' AND partition_timestamp = '".$GLOBAL["system_timestamp"]."') ORDER BY partition_device_id, partition_caption ",
                                                    "fields"=>array("10"=>array("name"=>"partition_device_id", "head"=>__("Index"),),
                                                                    "20"=>array("name"=>"partition_caption", "head"=>__("Drive Letter"),),
                                                                    "30"=>array("name"=>"partition_volume_name", "head"=>__("Description"),),
                                                                    "40"=>array("name"=>"partition_boot_partition", "head"=>__("Boot Partition"),),
                                                                    "50"=>array("name"=>"partition_bootable", "head"=>__("Bootable"),),
                                                                    "60"=>array("name"=>"partition_size", "head"=>__("Size"),),
                                                                    "70"=>array("name"=>"partition_file_system", "head"=>__("Filesystem"),),
                                                                    "80"=>array("name"=>"partition_free_space", "head"=>__("Free Space"),),
                                                                    "90"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "scsi_controller"=>array(
                                                    "headline"=>__("SCSI Controller"),
                                                    "sql"=>"SELECT * FROM scsi_controller, system  WHERE scsi_controller_uuid=system_uuid AND scsi_controller_uuid = '" . $pc . "' AND scsi_controller_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY scsi_controller_device_id",
                                                    "fields"=>array("10"=>array("name"=>"scsi_controller_caption", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"scsi_controller_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "30"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                  "optical_drive"=>array(
                                                    "headline"=>__("Optical Drive"),
                                                    "sql"=>"SELECT * FROM optical_drive, system WHERE optical_drive_uuid = '" . $pc . "' AND optical_drive_uuid = system_uuid AND optical_drive_timestamp = system_timestamp ORDER BY optical_drive_drive",
                                                    "fields"=>array("10"=>array("name"=>"optical_drive_drive", "head"=>__("Drive Letter"),),
                                                                    "20"=>array("name"=>"optical_drive_caption", "head"=>__("Manufacturer"),),
                                                                    "30"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "floppy"=>array(
                                                    "headline"=>__("Floppy Drive"),
                                                    "sql"=>"SELECT * FROM floppy WHERE floppy_uuid = '" . $pc . "' AND floppy_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"floppy_caption", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"floppy_description", "head"=>__("Description"),),
                                                                    "30"=>array("name"=>"floppy_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "tape_drive"=>array(
                                                    "headline"=>__("Tape Drive"),
                                                    "sql"=>"SELECT * FROM tape_drive WHERE tape_drive_uuid = '" . $pc . "' AND tape_drive_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY tape_drive_id",
                                                    "fields"=>array("10"=>array("name"=>"tape_drive_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "20"=>array("name"=>"tape_drive_caption", "head"=>__("Name"),),
                                                                    "30"=>array("name"=>"tape_drive_description", "head"=>__("Description"),),
                                                                    "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "processor"=>array(
                                                    "headline"=>__("Processor"),
                                                    "sql"=>"SELECT * FROM processor WHERE processor_uuid = '" . $_GET["pc"] . "' AND processor_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY processor_id",
                                                    "fields"=>array("10"=> array("name"=>"processor_device_id", "head"=>__("Index"),),
                                                                    "20"=> array("name"=>"processor_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "30"=> array("name"=>"processor_caption", "head"=>__("Type"),),
                                                                    "40"=> array("name"=>"processor_name", "head"=>__("Model"),),
                                                                    "50"=> array("name"=>"processor_socket_designation", "head"=>__("Socket Type"),),
                                                                    "60"=> array("name"=>"processor_max_clock_speed", "head"=>__("Max Speed MHz"),),
                                                                    "70"=> array("name"=>"processor_current_clock_speed", "head"=>__("Current Speed MHz"),),
                                                                    "80"=> array("name"=>"processor_ext_clock", "head"=>__("External Clock"),),
                                                                    "90"=> array("name"=>"processor_current_voltage", "head"=>__("Current Voltage"),),
                                                                    "100"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "bios"=>array(
                                                    "headline"=>__("Bios"),
                                                    "sql"=>"SELECT * FROM bios WHERE bios_uuid = '" . $pc . "' AND bios_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"bios_description", "head"=>__("Description"),),
                                                                    "20"=>array("name"=>"bios_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "30"=>array("name"=>"bios_serial_number", "head"=>__("Serial"),),
                                                                    "40"=>array("name"=>"bios_version", "head"=>__("Version"),),
                                                                    "50"=>array("name"=>"bios_sm_bios_version", "head"=>__("SM Caption"),),
                                                                    "60"=>array("name"=>"bios_asset_tag", "head"=>__("Asset Tag"),),
                                                                   ),
                                                    ),
                                   "memory"=>array(
                                                    "headline"=>__("Memory"),
                                                    "sql"=>"SELECT * FROM memory WHERE memory_uuid = '" . $pc . "' AND memory_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY memory_id",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"memory_tag", "head"=>__("Slot"),),
                                                                    "20"=>array("name"=>"memory_bank", "head"=>__("Bank"),),
                                                                    "30"=>array("name"=>"memory_form_factor", "head"=>__("Form Factor"),),
                                                                    "40"=>array("name"=>"memory_type", "head"=>__("Type"),),
                                                                    "50"=>array("name"=>"memory_detail", "head"=>__("Type Detail"),),
                                                                    "60"=>array("name"=>"memory_speed", "head"=>__("Speed"),),
                                                                    "70"=>array("name"=>"memory_capacity", "head"=>__("Capacity"),),
                                                                   ),
                                                    ),
                                  "network_card"=>array(
                                                    "headline"=>__("Network Card"),
                                                    "sql"=>"SELECT * FROM network_card WHERE net_uuid = '" . $_GET["pc"] . "' AND net_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY net_index ",
                                                    "image"=>"images/network_device_l.png",
                                                    "fields"=>array("10"=> array("name"=>"net_connection_id", "head"=>__("Connection ID"),),
                                                                    //"20"=> array("name"=>"net_index", "head"=>__("Index"),),
                                                                    "30"=> array("name"=>"net_description", "head"=>__("Description"),),
                                                                    "40"=> array("name"=>"net_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "50"=> array("name"=>"net_service_name", "head"=>__("Service Name"),),
                                                                    "60"=> array("name"=>"net_adapter_type", "head"=>__("Type"),),
                                                                    "70"=> array("name"=>"net_mac_address", "head"=>__("MAC Address"),),
                                                                    "80"=> array("name"=>"net_connection_status", "head"=>__("Connectivity status"),),
                                                                    "90"=> array("name"=>"net_speed", "head"=>__("Link speed"),),
                                                                    "100"=>array("name"=>"net_ip_enabled", "head"=>__("IP Enabled"),),
                                                                    "110"=>array("name"=>"net_ip_address", "head"=>__("IP address"),),
                                                                    "120"=>array("name"=>"net_ip_subnet", "head"=>__("Subnet Mask"),),
                                                                    "130"=>array("name"=>"net_ip_address_2", "head"=>__("IP address 2"),),
                                                                    "140"=>array("name"=>"net_ip_subnet_2", "head"=>__("Subnet Mask 2"),),
                                                                    "150"=>array("name"=>"net_ip_address_3", "head"=>__("IP address 3"),),
                                                                    "160"=>array("name"=>"net_ip_subnet_3", "head"=>__("Subnet Mask 3"),),
                                                                    //"170"=>array("name"=>"net_ip_metric", "head"=>__("Interface metric"),),
                                                                    "180"=>array("name"=>"net_gateway", "head"=>__("Gateway"),),
                                                                    //"190"=>array("name"=>"net_gateway_metric", "head"=>__("Gateway metric"),),
                                                                    "200"=>array("name"=>"net_gateway_2", "head"=>__("Gateway 2"),),
                                                                    //"210"=>array("name"=>"net_gateway_metric_2", "head"=>__("Gateway metric 2"),),
                                                                    "220"=>array("name"=>"net_gateway_3", "head"=>__("Gateway 3"),),
                                                                    //"230"=>array("name"=>"net_gateway_metric_3", "head"=>__("Gateway metric 3"),),
                                                                    "240"=>array("name"=>"net_dns_server", "head"=>__("Preferred DNS"),),
                                                                    "250"=>array("name"=>"net_dns_server_2", "head"=>__("Alternate DNS"),),
                                                                    "260"=>array("name"=>"net_dns_server_3", "head"=>__("Alternate DNS 2"),),
                                                                    //"270"=>array("name"=>"net_dns_domain", "head"=>__("Connection DNS Domain"),),
                                                                    //"280"=>array("name"=>"net_dns_domain_suffix", "head"=>__("Connection DNS Domain suffix"),),
                                                                    //"290"=>array("name"=>"net_dns_domain_suffix_2", "head"=>__("Connection DNS Domain suffix 2"),),
                                                                    //"300"=>array("name"=>"net_dns_domain_suffix_3", "head"=>__("Connection DNS Domain suffix 3"),),
                                                                    //"310"=>array("name"=>"net_dns_domain_reg_enabled", "head"=>__("DNS Domain reg enabled"),),
                                                                    //"320"=>array("name"=>"net_dns_domain_full_reg_enabled", "head"=>__("DNS Domain full reg enabled"),),
                                                                    "330"=>array("name"=>"net_wins_primary", "head"=>__("Primary WINS"),),
                                                                    "340"=>array("name"=>"net_wins_secondary", "head"=>__("Secondary WINS"),),
                                                                    "350"=>array("name"=>"net_wins_lmhosts_enabled", "head"=>__("LMHosts Lookup enabled"),),
                                                                    "360"=>array("name"=>"net_netbios_options", "head"=>__("Netbios over TCP/IP"),),
                                                                    "370"=>array("name"=>"net_dhcp_enabled", "head"=>__("DHCP enabled"),),
                                                                    "380"=>array("name"=>"net_dhcp_server", "head"=>__("DHCP Server"),),
                                                                    "390"=>array("name"=>"net_dhcp_lease_obtained", "head"=>__("DHCP Lease obtained"),),
                                                                    "400"=>array("name"=>"net_dhcp_lease_expires", "head"=>__("DHCP Lease expires"),),
                                                                    "410"=>array("name"=>"net_driver_provider", "head"=>__("Driver Provider"),),
                                                                    "420"=>array("name"=>"net_driver_version", "head"=>__("Driver Version"),),
                                                                    "430"=>array("name"=>"net_driver_date", "head"=>__("Driver Date"),),
                                                                    "440"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "video"=>array(
                                                    "headline"=>__("Video Adapter"),
                                                    "sql"=>"SELECT * FROM video WHERE video_uuid = '" . $pc . "' AND video_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"video_caption", "head"=>__("Model"),),
                                                                    "20"=>array("name"=>"video_adapter_ram", "head"=>__("RAM"),),
                                                                    "30"=>array("name"=>"video_current_horizontal_res", "head"=>__("Horizontal Resolution (x)"),),
                                                                    "40"=>array("name"=>"video_current_vertical_res", "head"=>__("Vertical Resolution (y)"),),
                                                                    "50"=>array("name"=>"video_current_refresh_rate", "head"=>__("Refresh Rate"),),
                                                                    "60"=>array("name"=>"video_current_number_colours", "head"=>__("Color Depth"),),
                                                                    "70"=>array("name"=>"video_driver_version", "head"=>__("Driver Version"),),
                                                                    "80"=>array("name"=>"video_driver_date", "head"=>__("Driver Date"),),
                                                                    "90"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "monitor"=>array(
                                                    "headline"=>__("Monitor"),
                                                    "sql"=>"SELECT * FROM monitor WHERE monitor_uuid = '" . $pc . "' AND monitor_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"monitor_model", "head"=>__("Model"),),
                                                                    "20"=>array("name"=>"monitor_serial", "head"=>__("Serial"),),
                                                                    "50"=>array("name"=>"monitor_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "60"=>array("name"=>"monitor_manufacture_date", "head"=>__("Date of Manufacture"),),
                                                                    "70"=>array("name"=>"monitor_date_purchased", "head"=>__("Date of Purchase"),),
                                                                    "80"=>array("name"=>"monitor_purchase_order_number", "head"=>__("Purchase Order Number"),),
                                                                    "90"=>array("name"=>"monitor_value", "head"=>__("Dollar Value"),),
                                                                    "100"=>array("name"=>"monitor_description", "head"=>__("Description"),),
                                                                    "110"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "sound"=>array(
                                                    "headline"=>__("Soundcard"),
                                                    "sql"=>"SELECT * FROM sound WHERE sound_uuid = '" . $pc . "' AND sound_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"sound_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"sound_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "30"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "keyboard"=>array(
                                                    "headline"=>__("Keyboard"),
                                                    "sql"=>"SELECT * FROM keyboard WHERE keyboard_uuid = '" . $pc . "' AND keyboard_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"keyboard_caption", "head"=>__("Type"),),
                                                                    "20"=>array("name"=>"keyboard_description", "head"=>__("Description"),),
                                                                    "30"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "mouse"=>array(
                                                    "headline"=>__("Mouse"),
                                                    "sql"=>"SELECT * FROM mouse WHERE mouse_uuid = '" . $pc . "' AND mouse_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"mouse_description", "head"=>__("Description"),),
                                                                    "20"=>array("name"=>"mouse_number_of_buttons", "head"=>__("Buttons"),),
                                                                    "30"=>array("name"=>"mouse_port", "head"=>__("Port"),),
                                                                    "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "modem"=>array(
                                                    "headline"=>__("Modem"),
                                                    "sql"=>"SELECT * FROM modem WHERE modem_uuid = '" . $pc . "' AND modem_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY modem_attached_to",
                                                    "fields"=>array("10"=>array("name"=>"modem_device_type", "head"=>__("Type"),),
                                                                    "20"=>array("name"=>"modem_description", "head"=>__("Description"),),
                                                                    "30"=>array("name"=>"modem_attached_to", "head"=>__("Port"),),
                                                                    "40"=>array("name"=>"modem_country_selected", "head"=>__("Country"),),
                                                                    "50"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "battery"=>array(
                                                    "headline"=>__("Battery"),
                                                    "sql"=>"SELECT * FROM battery WHERE battery_uuid = '" . $pc . "' AND battery_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                    "fields"=>array("10"=>array("name"=>"battery_description", "head"=>__("Description"),),
                                                                    "20"=>array("name"=>"battery_device_id", "head"=>__("ID"),),
                                                                   ),
                                                    ),
                                   "printer"=>array(
                                                    "headline"=>__("Printer"),
                                                    "sql"=>"SELECT * FROM other WHERE other_type = 'printer' AND other_linked_pc = '" . $pc . "' AND other_timestamp = '".$GLOBAL["system_timestamp"]."' ",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"other_description", "head"=>__("Description"),),
                                                                    "20"=>array("name"=>"other_p_port_name", "head"=>__("Port"),),
                                                                    "30"=>array("name"=>"other_p_shared", "head"=>__("Shared"),),
                                                                    "40"=>array("name"=>"other_p_share_name", "head"=>__("Share Name"),),
                                                                    "50"=>array("name"=>"other_model", "head"=>__("Driver Name"),),
																	"60"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "usb"=>array(
                                                    "headline"=>__("USB"),
                                                    "sql"=>"SELECT * FROM usb WHERE usb_uuid = '" . $pc . "' AND usb_timestamp = '".$GLOBAL["system_timestamp"]."' AND usb_manufacturer <> '(Standard system devices)' AND usb_caption <> 'HID-compliant consumer control device' AND usb_manufacturer <> '(Standard USB Host Controller)' ORDER BY usb_caption",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"usb_caption", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"usb_description", "head"=>__("Description"),),
                                                                    "30"=>array("name"=>"usb_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                    "installed_software"=>array(
                                                        "headline"=>__("Installed Software"),
                                                        "sql"=>"SELECT software_name, software_version, software_publisher FROM software, system WHERE system_uuid = '".$pc."' AND software_name NOT LIKE '%hotfix%' AND software_name NOT LIKE '%Service Pack%' AND software_name NOT REGEXP '[KB|Q][0-9]{6,}' AND software_uuid = system_uuid AND software_timestamp = system_timestamp GROUP BY software_name, software_version ",
                                                        "table_layout"=>"horizontal",
                                                        "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                       ),
                                                        ),
                                    "hotfixes_patches"=>array(
                                                        "headline"=>__("Hotfixes and Patches"),
                                                        "sql"=>"SELECT software_name, software_version, software_publisher FROM software, system WHERE system_uuid = '".$pc."' AND (software_name LIKE '%hotfix%' OR software_name LIKE '%Service Pack%' OR software_name REGEXP '[KB|Q][0-9]{6,}') AND software_uuid = system_uuid AND software_timestamp = system_timestamp GROUP BY software_name, software_version ",
                                                        "table_layout"=>"horizontal",
                                                        "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                       ),
                                                        ),
                                   "startup_software"=>array(
                                                    "headline"=>__("Run at startup"),
                                                    "sql"=>"SELECT * FROM startup WHERE startup_uuid = '".$pc."' AND startup_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY startup_caption",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"startup_caption", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"startup_user", "head"=>__("User"),),
                                                                    "30"=>array("name"=>"startup_location", "head"=>__("Location"),),
                                                                    "40"=>array("name"=>"startup_command", "head"=>__("Executable"),),
                                                                   ),
                                                    ),
                                   "uninstalled_software"=>array(
                                                    "headline"=>__("Uninstalled Software"),
                                                    "sql"=>"SELECT software_name, software_version, software_publisher FROM software, system WHERE system_uuid = '".$pc."' AND software_uuid = system_uuid AND software_timestamp <> system_timestamp GROUP BY software_name, software_version ",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                    "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                    "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "software_keys"=>array(
                                                    "headline"=>__("Keys"),
                                                    "sql"=>"SELECT ms_keys_name, ms_keys_cd_key, system_name, net_ip_address, system_uuid FROM ms_keys, system WHERE system_uuid LIKE '".urldecode($pc)."%' AND ms_keys_uuid = system_uuid AND ms_keys_timestamp = system_timestamp ",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"ms_keys_name", "head"=>__("Software"),),
                                                                    "20"=>array("name"=>"ms_keys_cd_key", "head"=>__("Key"),),
                                                                   ),
                                                    ),
                                   "ie_bho"=>array(
                                                    "headline"=>__("IE BHOs"),
                                                    "sql"=>"SELECT * FROM browser_helper_objects, system WHERE system_uuid = '".urldecode($pc)."' AND bho_uuid = system_uuid AND bho_timestamp = system_timestamp ORDER BY bho_program_file ",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"bho_program_file", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"bho_status", "head"=>__("Status"),),
                                                                   ),
                                                    ),
                                   "codecs"=>array(
                                                    "headline"=>__("Codecs"),
                                                    "sql"=>"SELECT software_name, software_version, software_publisher FROM software, system WHERE system_uuid = '".$pc."' AND software_name LIKE 'Codec%' AND software_uuid = system_uuid AND software_timestamp = system_timestamp GROUP BY software_name, software_version ",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                    "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                   ),
                                                    ),
                                   "services"=>array(
                                                    "headline"=>__("Services"),
                                                    "sql"=>"SELECT * FROM service, service_details WHERE sd_display_name = service_display_name AND service_uuid = '".$pc."' AND service_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY service_display_name",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"service_display_name", "head"=>__("Display Name"),),
                                                                    "20"=>array("name"=>"service_name", "head"=>__("Name"),),
                                                                    "30"=>array("name"=>"service_start_mode", "head"=>__("Start Mode"),),
                                                                    "40"=>array("name"=>"service_state", "head"=>__("State"),),
                                                                    "50"=>array("name"=>"service_start_name", "head"=>__("Logon As"),),
                                                                   ),
                                                    ),
                                   "os"=>array(
                                                    "headline"=>__("OS"),
                                                    "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $pc . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "fields"=>array("10"=>array("name"=>"system_os_name", "head"=>__("Operating System"),),
                                                                    "20"=>array("name"=>"system_registered_user", "head"=>__("Registered User"),),
                                                                    "30"=>array("name"=>"system_organisation", "head"=>__("Registered Organization"),),
                                                                    "40"=>array("name"=>"system_build_number", "head"=>__("OS Version (Build Number)"),),
                                                                    "50"=>array("name"=>"system_service_pack", "head"=>__("Service Pack"),),
																	"60"=>array("name"=>"system_os_arch", "head"=>__("OS Architecture"),),
                                                                    "70"=>array("name"=>"system_windows_directory", "head"=>__("Windows Directory"),),
                                                                    "80"=>array("name"=>"system_serial_number", "head"=>__("Windows Serial"),),
                                                                    "90"=>array("name"=>"date_system_install", "head"=>__("OS Installed On"),),
                                                                    "100"=>array("name"=>"system_language", "head"=>__("Language"),),
                                                                    "110"=>array("name"=>"time_caption", "head"=>__("Time Zone"),),
                                                                    "120"=>array("name"=>"time_daylight", "head"=>__("Daylight Savings Zone"),),
                                                                    "130"=>array("name"=>"system_last_boot", "head"=>__("Last Boot On"),),
                                                                   ),
                                                    ),
                                   "system_software"=>array(
                                                    "headline"=>__("System Software"),
                                                    "sql"=>"SELECT software_name, software_version
                                                            FROM software, system
                                                            WHERE system_uuid = '".$pc."' AND software_uuid = system_uuid AND software_timestamp = system_timestamp
                                                            AND (software_name LIKE 'Internet Explorer%' OR software_name LIKE 'DirectX%' OR software_name = 'Windows Media Player' 
                                                                 OR software_name LIKE 'MSXML%' OR software_name LIKE 'Microsoft .NET Framework%' OR software_name = 'MDAC'
                                                                 OR software_name = 'Windows DAC')
                                                            AND software_name NOT LIKE '%Language Pack%' AND software_name NOT LIKE '%hotfix%' 
                                                            ORDER BY software_name ",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                   ),
                                                    ),
                                   "shares"=>array(
                                                    "headline"=>__("Shared Folders"),
                                                    "sql"=>"SELECT * FROM shares WHERE shares_uuid = '".$pc."' AND shares_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY shares_path, shares_name",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"shares_name", "head"=>__("Share Name"),),
                                                                    "20"=>array("name"=>"shares_caption", "head"=>__("Description"),),
                                                                    "30"=>array("name"=>"shares_path", "head"=>__("Folder"),),
                                                                   ),
                                                    ),
                                   "scheduled_tasks"=>array(
                                                    "headline"=>__("Scheduled Tasks"),
                                                    "sql"=>"SELECT * FROM scheduled_task WHERE sched_task_uuid = '".$_REQUEST["pc"]."' AND sched_task_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY sched_task_name",
                                                    "fields"=>array("10"=>array("name"=>"sched_task_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"sched_task_next_run", "head"=>__("Next Run Time"),),
                                                                    "30"=>array("name"=>"sched_task_status", "head"=>__("Status"),),
                                                                    "40"=>array("name"=>"sched_task_last_run", "head"=>__("Last Run Time"),),
                                                                    "50"=>array("name"=>"sched_task_last_result", "head"=>__("Last Result"),),
                                                                    "60"=>array("name"=>"sched_task_creator", "head"=>__("Creator"),),
                                                                    "70"=>array("name"=>"sched_task_schedule", "head"=>__("Schedule"),),
                                                                    "80"=>array("name"=>"sched_task_task", "head"=>__("Task to Run"),),
                                                                    "90"=>array("name"=>"sched_task_state", "head"=>__("State"),),
                                                                    "100"=>array("name"=>"sched_task_runas", "head"=>__("Run As"),),
                                                                    "110"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "env_variables"=>array(
                                                    "headline"=>__("Environment Variables"),
                                                    "sql"=>"SELECT * FROM environment_variable WHERE env_var_uuid = '".$_REQUEST["pc"]."' AND env_var_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY env_var_name",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"env_var_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"env_var_value", "head"=>__("Value"),),
                                                                   ),
                                                    ),
                                   "event_logs"=>array(
                                                    "headline"=>__("Event Logs"),
                                                    "sql"=>"SELECT * FROM event_log WHERE evt_log_uuid = '".$_REQUEST["pc"]."' AND evt_log_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY evt_log_name",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"evt_log_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"evt_log_file_name", "head"=>__("File Name"),),
                                                                    "30"=>array("name"=>"evt_log_file_size", "head"=>__("File Size"),),
                                                                    "40"=>array("name"=>"evt_log_max_file_size", "head"=>__("Maximum File Size"),),
                                                                    "50"=>array("name"=>"evt_log_overwrite", "head"=>__("Overwrite Policy"),),
                                                                   ),
                                                    ),
                                   "ip_routes"=>array(
                                                    "headline"=>__("IP Routes"),
                                                    "sql"=>"SELECT * FROM ip_route WHERE ip_route_uuid = '".$_REQUEST["pc"]."' AND ip_route_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY ip_route_destination",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"ip_route_destination", "head"=>__("Destination"),),
                                                                    "20"=>array("name"=>"ip_route_mask", "head"=>__("Mask"),),
                                                                    "30"=>array("name"=>"ip_route_metric", "head"=>__("Metric"),),
                                                                    "40"=>array("name"=>"ip_route_next_hop", "head"=>__("Next Hop"),),
                                                                    "50"=>array("name"=>"ip_route_protocol", "head"=>__("Protocol"),),
                                                                    "60"=>array("name"=>"ip_route_type", "head"=>__("Type"),),
                                                                    "70"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "pagefile"=>array(
                                                    "headline"=>__("Pagefile"),
                                                    "sql"=>"SELECT * FROM pagefile WHERE pagefile_uuid = '".$_REQUEST["pc"]."' AND pagefile_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY pagefile_name",
                                                    "table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"pagefile_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"pagefile_initial_size", "head"=>__("Initial Size"),),
                                                                    "30"=>array("name"=>"pagefile_max_size", "head"=>__("Maximum Size"),),
                                                                   ),
                                                    ),
                                   "mapped"=>array(
                                                    "headline"=>__("Mapped Drives"),
                                                    "sql"=>"SELECT * FROM mapped WHERE mapped_uuid = '".$_REQUEST["pc"]."' AND mapped_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY mapped_username, mapped_device_id",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"mapped_username", "head"=>__("UserName"),),
                                                                    "20"=>array("name"=>"mapped_device_id", "head"=>__("Drive ID"),),
                                                                    "30"=>array("name"=>"mapped_provider_name", "head"=>__("UNC Path"),),
                                                                    "40"=>array("name"=>"mapped_connect_as", "head"=>__("Connected As"),),
                                                                    //"50"=>array("name"=>"mapped_file_system", "head"=>__("File System"),),
                                                                    //"60"=>array("name"=>"mapped_size", "head"=>__("Size"),),
                                                                    //"70"=>array("name"=>"mapped_free_space", "head"=>__("Free Space"),),
                                                                   ),
                                                    ),
                                   "win_firewall"=>array(
                                                    "headline"=>__("Windows Firewall"),
                                                    "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $pc . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                    "fields"=>array("10"=>array("name"=>"firewall_enabled_domain", "head"=>__("Domain - Firewall Enabled"),),
                                                                    "20"=>array("name"=>"firewall_disablenotifications_domain", "head"=>__("Domain - Notifications to User"),),
                                                                    "30"=>array("name"=>"firewall_donotallowexceptions_domain", "head"=>__("Domain - Exceptions Allowed"),),
                                                                    "40"=>array("name"=>"firewall_enabled_standard", "head"=>__("Standard - Firewall Enabled"),),
                                                                    "50"=>array("name"=>"firewall_disablenotifications_standard", "head"=>__("Standard - Notifications to User"),),
                                                                    "60"=>array("name"=>"firewall_donotallowexceptions_standard", "head"=>__("Standard - Exceptions Allowed"),),
                                                                   ),
                                                    ),
                                   "win_firewall_port_exceptions"=>array(
                                                    "headline"=>__("Windows Firewall Port Exceptions"),
                                                    "sql"=>"SELECT * FROM firewall_ports where port_uuid = '".$pc."' AND port_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY port_profile, port_number, port_protocol",
                                                    "fields"=>array("10"=>array("name"=>"port_profile", "head"=>__("Profile"),),
                                                                    "20"=>array("name"=>"port_number",  "head"=>__("Port"),),
                                                                    "30"=>array("name"=>"port_protocol", "head"=>__("Protocol"),),
                                                                    "40"=>array("name"=>"port_scope", "head"=>__("Scope"),),
                                                                    "50"=>array("name"=>"port_enabled", "head"=>__("State"),),
                                                                    "60"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "win_firewall_program_exceptions"=>array(
                                                    "headline"=>__("Windows Firewall Program Exceptions"),
                                                    "sql"=>"SELECT * FROM firewall_auth_app where firewall_app_uuid = '".$pc."' AND firewall_app_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY firewall_app_profile, firewall_app_name",
                                                    "fields"=>array("10"=>array("name"=>"firewall_app_profile", "head"=>__("Profile"),),
                                                                    "20"=>array("name"=>"firewall_app_name",  "head"=>__("Name"),),
                                                                    "30"=>array("name"=>"firewall_app_executable", "head"=>__("File"),),
                                                                    "40"=>array("name"=>"firewall_app_remote_address",  "head"=>__("Scope"),),
                                                                    "50"=>array("name"=>"firewall_app_enabled", "head"=>__("State"),),
                                                                    "60"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "firewall_other"=>array(
                                                    "headline"=>__("Other Firewalls"),
                                                    "sql"=>"SELECT * from software WHERE software_uuid = '" . $pc . "' AND software_timestamp = '".$GLOBAL["system_timestamp"]."'
                                                                                         AND (software_name LIKE '%ZoneAlarm%' 
                                                                                              OR software_name LIKE '%Internet Security%'
                                                                                              OR software_name LIKE '%Firewall%')",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                    "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                    "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "antivirus_xp"=>array(
                                                    "headline"=>__("Windows Security Center Registered Antivirus"),
                                                    "sql"=>"SELECT * from system WHERE system_uuid = '" . $pc . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."'  AND (virus_name <> '' OR virus_manufacturer <> '') ",
                                                    "fields"=>array("10"=>array("name"=>"virus_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"virus_version", "head"=>__("Version"),),
                                                                    "30"=>array("name"=>"virus_manufacturer", "head"=>__("Manufacturer"),),
                                                                    "40"=>array("name"=>"virus_uptodate", "head"=>__("Up-to-date"),),
                                                                   ),
                                                    ),
                                   "antivirus_other"=>array(
                                                    "headline"=>__("Other Antivirus"),
                                                    "sql"=>"SELECT * from software WHERE software_uuid = '" . $pc . "' AND software_timestamp = '".$GLOBAL["system_timestamp"]."'
                                                                                         AND (software_name LIKE '%Avast%'
                                                                                              OR software_name LIKE '%Antivir%'
                                                                                              OR software_name LIKE '%Internet Security%'
                                                                                              OR software_name LIKE '%Virus%'
                                                                                              OR software_name LIKE '%Client Security%')",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                    "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                    "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "auto_updating"=>array(
                                                        "headline"=>__("Automatic Updating Client Settings"),
                                                        "sql"=>"SELECT * from auto_updating WHERE au_uuid = '" . $_GET["pc"] . "' AND au_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                        "fields"=>array("10"=> array("name"=>"au_gpo_configured", "head"=>__("AU Client is configured by a GPO"),),
                                                                        "20"=> array("name"=>"au_enabled", "head"=>__("AU Client is enabled"),),
                                                                        "30"=> array("name"=>"au_behaviour", "head"=>__("AU Client behaviour"),),
                                                                        "40"=> array("name"=>"au_sched_install_day", "head"=>__("Scheduled install day"),),
                                                                        "50"=> array("name"=>"au_sched_install_time", "head"=>__("Scheduled install time"),),
                                                                        "60"=> array("name"=>"au_use_wuserver", "head"=>__("Use a WSUS server"),),
                                                                        "70"=> array("name"=>"au_wuserver", "head"=>__("WSUS server"),),
                                                                        "80"=> array("name"=>"au_wustatusserver", "head"=>__("WSUS Status server"),),
                                                                        "90"=> array("name"=>"au_target_group", "head"=>__("WSUS Target Group"),),
                                                                        "100"=>array("name"=>"au_elevate_nonadmins", "head"=>__("Allow non-admins to receive update notifications"),),
                                                                        "110"=>array("name"=>"au_auto_install", "head"=>__("Automatic installation of minor updates"),),
                                                                        "120"=>array("name"=>"au_detection_frequency", "head"=>__("Automatic updates detection frequency (hours)"),),
                                                                        "130"=>array("name"=>"au_reboot_timeout", "head"=>__("Delay before prompting again for restart (minutes)"),),
                                                                        "140"=>array("name"=>"au_noautoreboot", "head"=>__("No auto-restart for scheduled installations"),),
                                                                       ),
                                                        ),
                                   "nmap"=>array(
                                                    "headline"=>__("Open Ports discovered by Nmap"),
                                                    "sql"=>"SELECT * from nmap_ports WHERE nmap_other_id = '" . $pc . "' ORDER BY nmap_port_number, nmap_port_proto, nmap_port_name, nmap_port_version ",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"nmap_port_number", "head"=>__("Port"),),
                                                                    "20"=>array("name"=>"nmap_port_proto", "head"=>__("Protocol"),),
                                                                    "30"=>array("name"=>"nmap_port_name", "head"=>__("Service"),),
                                                                    "40"=>array("name"=>"nmap_port_version", "head"=>__("Version"),),
                                                                    "50"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "users"=>array(
                                                    "headline"=>__("Users"),
                                                    "sql"=>"SELECT * FROM users WHERE users_uuid = '".$pc."' AND users_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY users_name",
                                                    "fields"=>array("10"=>array("name"=>"users_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"users_full_name", "head"=>__("Full Name"),),
                                                                    "30"=>array("name"=>"users_sid", "head"=>__("SID"),),
                                                                    "40"=>array("name"=>"users_disabled", "head"=>__("Disabled"),),
                                                                    "50"=>array("name"=>"users_password_changeable", "head"=>__("Password changeable"),),
                                                                    "60"=>array("name"=>"users_password_required", "head"=>__("Password required"),),
                                                                    //"70"=>array("name"=>"ud_description", "head"=>__("Description"),),
																	"80"=>array("name"=>"users_password_expires", "head"=>__("Password expires"),),
                                                                    "90"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "groups"=>array(
                                                    "headline"=>__("Groups"),
                                                    "sql"=>"SELECT * FROM groups WHERE groups_uuid = '".$pc."' AND groups_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY groups_name ",
													//"table_layout"=>"horizontal",
                                                    "fields"=>array("10"=>array("name"=>"groups_name", "head"=>__("Name"),),
                                                                    "20"=>array("name"=>"groups_members", "head"=>__("Members"),),
                                                                    //"30"=>array("name"=>"gd_description", "head"=>__("Description"),),
																	"40"=>array("name"=>"groups_sid", "head"=>__("SID"),),
                                                                    "50"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                    ),
                                   "iis"=>array(
                                                "headline"=>__("IIS server"),
                                                "sql"=>"SELECT iis_version FROM system WHERE system_uuid = '" . $pc . "' OR system_name = '" . $pc . "' ",
                                                "fields"=>array("10"=>array("name"=>"iis_version", "head"=>__("IIS version"),),
                                                                   ),
                                                    ),
                                   "iis_2"=>array(
                                                  "headline"=>__("IIS installed features"),
                                                  "sql"=>"SELECT * FROM service 
                                                          WHERE service_uuid = '".$pc."' AND service_timestamp = '".$GLOBAL["system_timestamp"]."' 
                                                                AND (service_name = 'W3SVC' OR service_name = 'MSFTPSVC' OR service_name = 'SMTPSVC' 
                                                                     OR service_name = 'NNTPSVC' OR service_name = 'BITS' ) 
                                                          ORDER BY service_display_name",
                                                  "table_layout"=>"horizontal",
                                                  "fields"=>array("10"=>array("name"=>"service_display_name", "head"=>__("Service Display Name"),),
                                                                  "20"=>array("name"=>"service_name", "head"=>__("Service Name"),),
                                                                  "30"=>array("name"=>"service_start_mode", "head"=>__("Start Mode"),),
                                                                  "40"=>array("name"=>"service_state", "head"=>__("State"),),
                                                                 ),
                                                  ),
                                   "iis_web_ext"=>array(
                                                        "headline"=>__("IIS Web Service Extensions"),
                                                        "sql"=>"SELECT * FROM iis_web_ext WHERE iis_web_ext_uuid = '" . $_GET["pc"] . "' AND iis_web_ext_timestamp = '".$GLOBAL["system_timestamp"]."' 
                                                                ORDER BY iis_web_ext_desc",
														//"table_layout"=>"horizontal",
                                                        "fields"=>array("10"=>array("name"=>"iis_web_ext_desc", "head"=>__("Description"),),
                                                                        "20"=>array("name"=>"iis_web_ext_path", "head"=>__("Path"),),
                                                                        "30"=>array("name"=>"iis_web_ext_access", "head"=>__("Access"),),
                                                                        "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                       ),
                                                        ),
                                   "iis_web"=>array(
                                                   "headline"=>__("IIS Web Sites"),
                                                   "sql"=>"SELECT * FROM iis WHERE iis_uuid = '".$pc."' AND iis_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY iis_site",
                                                   "fields"=>array("10"=>array("name"=>"iis_site", "head"=>__("Site ID"),),
                                                                   "20"=> array("name"=>"iis_description", "head"=>__("Description"),),
                                                                   "30"=> array("name"=>"iis_site_state", "head"=>__("Site State"),),
                                                                   "40"=> array("name"=>"iis_home_directory", "head"=>__("Home Directory"),),
                                                                   "50"=> array("name"=>"iis_directory_browsing", "head"=>__("Directory Browsing"),),
                                                                   "60"=> array("name"=>"iis_default_documents", "head"=>__("Default Documents"),),
                                                                   "70"=> array("name"=>"iis_logging_enabled", "head"=>__("Logging Enabled"),),
                                                                   "80"=> array("name"=>"iis_logging_format", "head"=>__("Logging Format"),),
                                                                   "90"=> array("name"=>"iis_logging_time_period", "head"=>__("Logging Period"),),
                                                                   "100"=>array("name"=>"iis_logging_dir", "head"=>__("Logging Directory"),),
                                                                   "110"=>array("name"=>"iis_site_app_pool", "head"=>__("Application Pool"),),
                                                                   "120"=>array("name"=>"iis_site_anonymous_user", "head"=>__("Anonymous User"),),
                                                                   "130"=>array("name"=>"iis_site_anonymous_auth", "head"=>__("Anonymous Auth. Enabled"),),
                                                                   "140"=>array("name"=>"iis_site_basic_auth", "head"=>__("Basic Auth. Enabled"),),
                                                                   "150"=>array("name"=>"iis_site_ntlm_auth", "head"=>__("NTLM Auth. Enabled"),),
                                                                   "160"=>array("name"=>"iis_site_ssl_en", "head"=>__("SSL Comm. Enabled"),),
                                                                   "170"=>array("name"=>"iis_site_ssl128_en", "head"=>__("SSL 128 bit Enabled"),),
                                                                   "180"=>array("name"=>"iis_secure_ip", "head"=>__("SSL IP address"),),
                                                                   "190"=>array("name"=>"iis_secure_port", "head"=>__("SSL Port"),),
                                                                   "200"=>array("name"=>" ", "head"=>__(" "),),
                                                                  ),
                                                ),
                                   "iis_ip"=>array(
                                                   "headline"=>__("IIS IP settings"),
                                                   "sql"=>"SELECT iis_ip_site, iis_ip_ip_address, iis_ip_port, iis_ip_host_header FROM iis_ip where iis_ip_uuid = '".$pc."' AND iis_ip_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY iis_ip_site ",
													//"table_layout"=>"horizontal",
                                                   "fields"=>array("10"=>array("name"=>"iis_ip_site", "head"=>__("Site ID"),),
                                                                   "20"=>array("name"=>"iis_ip_ip_address", "head"=>__("IP Address"),),
                                                                   "30"=>array("name"=>"iis_ip_port", "head"=>__("Port"),),
                                                                   "40"=>array("name"=>"iis_ip_host_header", "head"=>__("Host Header"),),
                                                                   "50"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                   ),
                                   "iis_vd"=>array(
                                                   "headline"=>__("IIS Virtual Directories"),
                                                   "sql"=>"SELECT * from iis_vd where iis_vd_uuid = '".$pc."' AND iis_vd_timestamp = '".$GLOBAL["system_timestamp"]."' ORDER BY iis_vd_site ",
													//"table_layout"=>"horizontal",
                                                   "fields"=>array("10"=>array("name"=>"iis_vd_site", "head"=>__("Site ID"),),
                                                                   "20"=>array("name"=>"iis_vd_name", "head"=>__("Name"),),
                                                                   "30"=>array("name"=>"iis_vd_path", "head"=>__("Path"),),
                                                                   "40"=>array("name"=>" ", "head"=>__(" "),),
                                                                   ),
                                                   ),
                                 ),
                  );
?>
