<?php
/**********************************************************************************************************
Recent Changes:

[Edoardo]	30/01/2008	Added Chassis, Mobo and Onboard devices items in yhe Hardware menu
						Added Scheduled Tasks, Env. vars, Event Logs. IP routes and Pagefile items in the OS settings menu
[Edoardo]	13/04/2008	Added the Security - Automatic Updating menu item
[Edoardo]	23/05/2008	Added the Queries - All MS Windows local Administrators menu item
[Edoardo]	06/06/2008	Added the Queries - All Mapped drives menu item
[Edoardo]	07/06/2008	Changed some Hardware and OS Settings icons	
[Edoardo]	13/02/2009	Moved the All partitions menu item from Statistics to Queries
[Edoardo]	12/03/2009	Fixed the Queries - All mapped drives menu item - Fix by Michalak
[Edoardo]	10/10/2009	Added the Other items - All modems menu item
[Edoardo]	10/10/2009	Fixed Security - Firewall menu to include Windows Firewall system settings
[Edoardo]	22/05/2010	Added the Statistics - Printer model menu item
[Edoardo]	28/05/2010	Added the Queries - All Hard Disks menu item
	
					
**********************************************************************************************************/
if(!isset($name)) $name = "";
$menue_array = array(

  "machine" => array(
      "10" => array("name"=>"Hardware",
                    "link"=>"system.php?pc=$pc&amp;view=hardware",
                    "image"=>"fa-microchip",
                    "class"=>"menuparent",
                    "childs"=>array("05"=>array("name"=>"All", "link"=>"system.php?pc=$pc&amp;view=hardware", "image"=>"fa-sitemap", "title"=>"",),
                                    "06"=>array("name"=>"Chassis", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=chassis", "image"=>"fa-cube", "title"=>"",),
                                    "07"=>array("name"=>"Motherboard", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=motherboard", "image"=>"fa-microchip", "title"=>"",),
                                    "08"=>array("name"=>"Onboard Devices", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=onboard_device", "image"=>"fa-cogs", "title"=>"",),
                                    "10"=>array("name"=>"Fixed Disks", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=hard_drive", "image"=>"fa-navicon", "title"=>"",),
                                    "20"=>array("name"=>"Partitions", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=partition", "image"=>"fa-list-ol", "title"=>"",),
                                    "30"=>array("name"=>"SCSI Controller", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=scsi_controller", "image"=>"fa-cog", "title"=>"",),
                                    "40"=>array("name"=>"Optical Drive", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=optical_drive", "image"=>"fa-circle-thin", "title"=>"",),
                                    "50"=>array("name"=>"Floppy Drive", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=floppy", "image"=>"fa-save", "title"=>"",),
                                    "60"=>array("name"=>"Tape Drive", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=tape_drive", "image"=>"fa-simplybuilt", "title"=>"",),
                                    "70"=>array("name"=>"Processor", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=processor", "image"=>"fa-fighter-jet", "title"=>"",),
                                    "80"=>array("name"=>"Bios", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=bios", "image"=>"fa-cog", "title"=>"",),
                                    "90"=>array("name"=>"Memory", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=memory", "image"=>"fa-stack-exchange", "title"=>"",),
                                    "100"=>array("name"=>"Network Card", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=network_card", "image"=>"fa-wifi", "title"=>"",),
                                    "105"=>array("name"=>"Gateway", "link"=>"list.php?view=statistic_gateway", "image"=>"fa-external-link-square", "title"=>"",), 
                                    "110"=>array("name"=>"Video Adapter", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=video", "image"=>"fa-eye", "title"=>"",),
                                    "120"=>array("name"=>"Monitor", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=monitor", "image"=>"fa-television", "title"=>"",),
                                    "130"=>array("name"=>"Soundcard", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=sound", "image"=>"fa-volume-up", "title"=>"",),
                                    "140"=>array("name"=>"Keyboard and Mouse", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=keyboard,mouse", "image"=>"fa-keyboard-o", "title"=>"",),
                                    "150"=>array("name"=>"Modem", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=modem", "image"=>"fa-phone", "title"=>"",),
                                    "160"=>array("name"=>"Battery", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=battery", "image"=>"fa-battery", "title"=>"",),
                                    "170"=>array("name"=>"Printer", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=printer", "image"=>"fa-print", "title"=>"",),
                                    "180"=>array("name"=>"USB", "link"=>"system.php?pc=$pc&amp;view=hardware&amp;category=usb", "image"=>"fa-usb", "title"=>"",),
                              ),
              ),
      "20" => array("name"=>"Software",
                    "link"=>"list.php?pc=$pc&amp;view=software_for_system",
                    "image"=>"fa-code",
                    "class"=>"menuparent",
                    "childs"=>array("10"=>array("name"=>"Installed Software", "link"=>"list.php?pc=$pc&amp;view=software_for_system", "image"=>"fa-archive", "title"=>"",),
									"11"=>array("name"=>"All Software versions", "link"=>"list.php?pc=$pc&amp;view=softwareapps_for_system", "image"=>"fa-folder-open", "title"=>"Softwareversionen",),
									"12"=>array("name"=>"Installed ModernApps", "link"=>"list.php?pc=$pc&amp;view=softwareapps_for_system", "image"=>"fa-windows", "title"=>"Modern Apps",),
                                    "20"=>array("name"=>"System Components", "link"=>"list.php?pc=$pc&amp;view=syscomp_for_system", "image"=>"fa-wrench", "title"=>"",),
                                    "30"=>array("name"=>"Hotfixes &amp; Patches", "link"=>"list.php?pc=$pc&amp;view=hotfixes_patches_for_system", "image"=>"fa-bug", "title"=>"",),
                                    "40"=>array("name"=>"Run at Startup", "link"=>"list.php?pc=$pc&amp;view=startupsoftware_for_system", "image"=>"fa-cog", "title"=>"",),
                                    "50"=>array("name"=>"Software Audit-Trail", "link"=>"list.php?pc=$pc&amp;view=software_audit_system_trail", "image"=>"fa-file-text-o", "title"=>"",),
                                    "60"=>array("name"=>"Uninstalled Software", "link"=>"list.php?pc=$pc&amp;view=software_uninstalled_for_system", "image"=>"fa-scissors", "title"=>"deinstallierte Programme",),
                                    "70"=>array("name"=>"Keys", "link"=>"list.php?pc=$pc&amp;view=keys_for_system", "image"=>"fa-key", "title"=>"Lizenzschlüssel",),
                                    "90"=>array("name"=>"Codecs", "link"=>"list.php?pc=$pc&amp;view=codecs_for_system", "image"=>"fa-volume-up", "title"=>"",),
                                    "100"=>array("name"=>"Services", "link"=>"list.php?pc=$pc&amp;view=services_for_system", "image"=>"fa-cogs", "title"=>"",),
                           ),
              ),
      "30" => array("name"=>"OS Settings",
                    "link"=>"system.php?pc=$pc&amp;view=os",
                    "image"=>"fa-windows",
                    "class"=>"menuparent",
                    "childs"=>array("10"=>array("name"=>"All", "link"=>"system.php?pc=$pc&amp;view=os", "image"=>"fa-sitemap", "title"=>"",),
                                    "20"=>array("name"=>"OS Information", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=os", "image"=>"fa-windows", "title"=>"",),
                                    "30"=>array("name"=>"Software", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=software", "image"=>"fa-archive", "title"=>"",),
                                    "40"=>array("name"=>"Shared Drives", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=shares", "image"=>"fa-folder", "title"=>"",),
                                    "50"=>array("name"=>"Scheduled Tasks", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=scheduled_tasks", "image"=>"fa-clock-o", "title"=>"",),
                                    "60"=>array("name"=>"Env. Variables", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=env_variables", "image"=>"fa-code", "title"=>"",),
                                    "70"=>array("name"=>"Event Logs", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=event_logs", "image"=>"fa-file-o", "title"=>"",),
                                    "80"=>array("name"=>"IP Routes", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=ip_routes", "image"=>"fa-folder-open-o", "title"=>"",),
                                    "90"=>array("name"=>"Pagefile", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=pagefile", "image"=>"fa-file-text-o", "title"=>"",),
                                    "100"=>array("name"=>"Mapped Drives", "link"=>"system.php?pc=$pc&amp;view=os&amp;category=mapped", "image"=>"fa-folder-open", "title"=>"",),

                             ),
              ),
      "50" => array("name"=>"Security",
                    "link"=>"system.php?pc=$pc&amp;view=security",
                    "image"=>"fa-shield",
                    "class"=>"menuparent",
                    "childs"=>array("10"=>array("name"=>"All", "link"=>"system.php?pc=$pc&amp;view=security&amp;category=", "image"=>"fa-sitemap", "title"=>"",),
                                    "20"=>array("name"=>"Firewall", "link"=>"system.php?pc=$pc&amp;view=security&amp;category=win_firewall,firewall_other", "image"=>"fa-fire", "title"=>"",),
                                    "30"=>array("name"=>"Antivirus", "link"=>"system.php?pc=$pc&amp;view=security&amp;category=antivirus_xp,antivirus_other", "image"=>"fa-shield", "title"=>"",),
                                    "40"=>array("name"=>"Automatic Updating", "link"=>"system.php?pc=$pc&amp;view=security&amp;category=auto_updating", "image"=>"fa-cog", "title"=>"",),
                                    "50"=>array("name"=>"Portscan", "link"=>"system.php?pc=$pc&amp;view=security&amp;category=nmap", "image"=>"fa-eye", "title"=>"",),
                              ),
              ),
      "60" => array("name"=>"Users &amp; Groups",
                    "link"=>"system.php?pc=$pc&amp;view=users_groups",
                    "image"=>"fa-user",
                    "class"=>"menuparent",
                    "childs"=>array("10"=>array("name"=>"All", "link"=>"system.php?pc=$pc&amp;view=users_groups&amp;category=", "image"=>"fa-sitemap", "title"=>"",),
                                    "20"=>array("name"=>"Users", "link"=>"system.php?pc=$pc&amp;view=users_groups&amp;category=users", "image"=>"fa-user", "title"=>"",),
                                    "30"=>array("name"=>"Groups", "link"=>"system.php?pc=$pc&amp;view=users_groups&amp;category=groups", "image"=>"fa-group", "title"=>"",),
                              ),
              ),
      "70" => array("name"=>"IIS Settings",
                    "link"=>"system.php?pc=$pc&amp;view=iis",
                    "image"=>"fa-internet-explorer",
                    "title"=>"",
              ),
      "80" => array("name"=>"Disk Usage Graphs",
                    "link"=>"system_graphs.php?pc=$pc",
                    "image"=>"fa-navicon",
                    "title"=>"",
              ),
      "90" => array("name"=>"Audit Trail",
                    "link"=>"./list.php?pc=$pc&amp;view=audit_trail_for_system",
                    "image"=>"fa-clock-o",
                    "title"=>"",
              ),
  ),
  "misc" => array(

      "10" => array("name"=>"List Hardware", "image"=>"fa-laptop",
                    "link"=>"./list.php?view=all_systems_more",
                    "title"=>"Hardware für alle Windows-Rechner ",
                    "class"=>"menuparent",
                    "childs"=>array(
                                    "10"=>array("name"=>"All Systems More Info", "link"=>"./list.php?view=all_systems_more", "image"=>"fa-sitemap", "title"=>"All Audited Systems More Info",),
                                    "12"=>array("name"=>"All Partitions", "link"=>"./list.php?view=all_partition_space", "image"=>"fa-list-ol", "title"=>"All Partitions",),
                                    "20"=>array("name"=>"All Servers", "link"=>"./list.php?view=all_servers", "image"=>"fa-server", "title"=>"All Servers",),
                                    "22"=>array("name"=>"All Win-Clients", "link"=>"./list.php?view=all_win_clients", "image"=>"fa-desktop", "title"=>"All Win-PCs-Laptops",),
                                    "30"=>array("name"=>"All Win-Workstations", "link"=>"./list.php?view=all_win_workstations", "image"=>"fa-desktop", "title"=>"All Win-Workstations",),
                                    "40"=>array("name"=>"All Laptops", "link"=>"./list.php?view=all_laptops", "image"=>"fa-laptop", "title"=>"All Laptops",),
									"50"=>array("name"=>"All Audited Systems", "link"=>"./list.php?view=all_systems", "image"=>"fa-sitemap", "title"=>"All Audited Systems",),
                                    "60"=>array("name"=>"All Systems Manual Fields", "link"=>"./list.php?view=all_systems_manual_fields", "image"=>"fa-hand-pointer-o", "title"=>"All Audited Systems More Info",),
                                    "70"=>array("name"=>"All Hard Disks", "link"=>"./list.php?view=all_hard_disks", "image"=>"fa-navicon", "title"=>"All Hard Disks",),
                              ),
              ),
      "11" => array("name"=>"List Software", "image"=>"fa-code",
                    "link"=>"list.php?view=all_software",
                    "title"=>"Software auf allen Windows Rechnern",
                    "class"=>"menuparent",
                    "childs"=>array("60"=>array("name"=>"All Software", "link"=>"./list.php?view=all_software", "image"=>"fa-archive", "title"=>" All Software",),
									"70"=>array("name"=>"All Software w/ Hosts", "link"=>"./list.php?view=all_software_hosts", "image"=>"fa-folder-open", "title"=>"All Software with Hosts",),
									"72"=>array("name"=>"All Software short", "link"=>"./list.php?view=all_software-short", "image"=>"fa-folder", "title"=>" All Software Shortlist",),
                                    "74"=>array("name"=>"All Software versions", "link"=>"./list.php?view=all_softwareversionen", "image"=>"fa-road", "title"=>"All Software versions imported from PB",),
                                    "76"=>array("name"=>"All Modern Apps", "link"=>"./list.php?view=all_softwareapps", "image"=>"fa-windows", "title"=>" All Modern Apps",),
                                    "80"=>array("name"=>"All SW Patches", "link"=>"./list.php?view=all_hotfixes_patches", "image"=>"fa-bug", "title"=>"All Hotfixes &amp; Patches",),
                                    "85"=>array("name"=>"All SW Patches w/ Hosts", "link"=>"./list.php?view=all_hotfixes_patches", "image"=>"fa-bug", "title"=>"All Hotfixes &amp; Patches with Hosts",),
                                    "90"=>array("name"=>"All Anti Virus Status", "link"=>"./list.php?view=all_systems_virus_uptodate", "image"=>"fa-life-saver", "title"=>" All Anti Virus Software",),
                                    "110"=>array("name"=>"All Services", "link"=>"./list.php?view=all_services", "image"=>"fa-gears", "title"=>"All Services",),
                                    "120"=>array("name"=>"All Scheduled Tasks", "link"=>"list.php?pc=$pc&amp;view=all_sch_tasks", "image"=>"fa-bell", "title"=>"",),
                                    "130"=>array("name"=>"All Software Keys", "link"=>"./list.php?view=all_keys", "image"=>"fa-key", "title"=>"All Keys",),
                                    "140"=>array("name"=>"All MS Office Keys", "link"=>"./list.php?view=keys_for_software&amp;type=office%&amp;headline_addition=Office", "image"=>"fa-file-word-o", "title"=>"All Office Keys",),
                                    "150"=>array("name"=>"All MS Windows Keys", "link"=>"./list.php?view=keys_for_software&amp;type=windows%&amp;headline_addition=Windows", "image"=>"fa-windows", "title"=>"All Windows Keys",),
                                    "160"=>array("name"=>"All MS Windows Shares", "link"=>"./list.php?view=all_network_shares", "image"=>"fa-share-square", "title"=>"All Windows Shares by Host",),
                                    "170"=>array("name"=>"All MS Windows Admins", "link"=>"./list.php?view=all_win_admins", "image"=>"fa-user-secret", "title"=>"All Admins by Host",),
                                    "180"=>array("name"=>"All Mapped Drives", "link"=>"./list.php?view=all_mapped_drives", "image"=>"fa-folder-open-o", "title"=>"All Mapped Drives by Host",),
                                    "190"=>array("name"=>"All LDAP Systems", "link"=>"./list.php?view=ldap_computers", "image"=>"fa-desktop", "title"=>"All LDAP Audited Systems",),
                                    "200"=>array("name"=>"All LDAP Users", "link"=>"./list.php?view=ldap_users", "image"=>"fa-user", "title"=>"All LDAP Audited Users",),
                              ),
              ),


	  "20" => array("name"=>"Other Items","image"=>"fa-print",
                    "link"=>"list.php?view=other_networked",
                    "class"=>"menuparent",
                    "title"=>"für Nicht-Windows-Geräte",
                    "childs"=>array("10"=>array("name"=>"Printers", "link"=>"./list.php?view=all_printers", "image"=>"fa-print", "title"=>"List all Printer",),
                                    "15"=>array("name"=>"Printers IPv4", "link"=>"./list.php?view=all_printers_ipv4", "image"=>"fa-lg fa-print", "title"=>"List all IPv4 Printers",),
                                    "40"=>array("name"=>"Networked Items", "link"=>"./list.php?view=other_networked", "image"=>"fa-plug", "title"=>"List all other networked devices",),
                                    "50"=>array("name"=>"Non-Networked", "link"=>"./list.php?view=other_non_networked", "image"=>"fa-usb", "title"=>"List all other non-networked devices",),
                                    "60"=>array("name"=>"All Other Devices", "link"=>"./list.php?view=other_all", "image"=>"fa-cubes", "title"=>"List all other devices",),
                                    "70"=>array("name"=>"Monitors", "link"=>"./list.php?view=all_monitors", "image"=>"fa-television", "title"=>"List all monitors",),
                                    "80"=>array("name"=>"Modems", "link"=>"./list.php?view=all_modems", "image"=>"fa-phone", "title"=>"List all Modems",),								
                              ),
              ),
      "28" => array("name"=>"Statistics","image"=>"fa-bar-chart",
                    "link"=>"list.php?view=statistic_gateway",
                    "title"=>"diverse Statistiken",
                    "class"=>"menuparent",
                    "childs"=>array(
                                    "11"=>array("name"=>"Gateway", "link"=>"list.php?view=statistic_gateway", "image"=>"fa-external-link-square", "title"=>"Netzwerke-Übersicht",), 
                                    "15"=>array("name"=>"Java Versions", "link"=>"./list.php?view=statistic_java", "image"=>"fa-coffee", "title"=>"Java Versions",),
                                    "20"=>array("name"=>"Adobe Flash Player Versions", "link"=>"./list.php?view=statistic_adobe_flash_player", "image"=>"fa-flash", "title"=>"Adobe Flash Player Versions",),
                                    "25"=>array("name"=>"Adobe Reader Versions", "link"=>"./list.php?view=statistic_adobe_reader", "image"=>"fa-file-pdf-o", "title"=>"Adobe Reader Versions",),
                                    "27"=>array("name"=>"Msoffice Versions", "link"=>"./list.php?view=statistic_microsoftoffice", "image"=>"fa-file-word-o", "title"=>"Microsoft Office Versions",),
                                    "28"=>array("name"=>"Libreoffice Versions", "link"=>"./list.php?view=statistic_openoffice.org", "image"=>"fa-file-text-o", "title"=>"Libreoffice Versions",),
                                    "30"=>array("name"=>"GoogleChrome Versions", "link"=>"./list.php?view=statistic_chrome", "image"=>"fa-chrome", "title"=>"Google Chrome Versions",),
                                    "35"=>array("name"=>"Edge on Chromium Versions", "link"=>"./list.php?view=statistic_edgenew", "image"=>"fa-edge", "title"=>"Edge on Chromium Versions",),
                                    "40"=>array("name"=>"IE Versions", "link"=>"./list.php?view=statistic_ie", "image"=>"fa-internet-explorer", "title"=>"Internet Explorer Versions",),
                                    "45"=>array("name"=>"Firefox Versions", "link"=>"./list.php?view=statistic_firefox", "image"=>"fa-firefox", "title"=>"Mozilla Firefox Versions",),
                                    "47"=>array("name"=>"Opera/Vivaldi Versions", "link"=>"./list.php?view=statistic_opera", "image"=>"fa-opera", "title"=>"Opera/Vivaldi Versions",),
                                    "49"=>array("name"=>"apple Safari Versions", "link"=>"./list.php?view=statistic_safari", "image"=>"fa-safari", "title"=>"Safari Versions",),
                                    "65"=>array("name"=>"Thunderbird Versions", "link"=>"./list.php?view=statistic_thunderbird", "image"=>"fa-rebel", "title"=>"Mozilla Thunderbird Versions",),
									"67"=>array("name"=>"OS Type", "link"=>"./list.php?view=statistic_os", "image"=>"fa-windows", "title"=>"OS Type",),
                                    "70"=>array("name"=>"Printer Models", "link"=>"list.php?view=statistic_printer", "image"=>"fa-print", "title"=>"Printer Models",), 
                                    "75"=>array("name"=>"Memory Size", "link"=>"./list.php?view=statistic_memory", "image"=>"fa-stack-exchange", "title"=>"Memory Size",),
                                    "80"=>array("name"=>"Processor Types", "link"=>"./list.php?view=statistic_processor", "image"=>"fa-microchip", "title"=>"Processor Types",),
                                    "85"=>array("name"=>"Hard Drive", "link"=>"./list.php?view=statistic_harddrive", "image"=>"fa-navicon", "title"=>"Hard Drive",),
                                    "87"=>array("name"=>"DNS and Gateways", "link"=>"./list.php?view=systems_for_gateway", "image"=>"fa-sitemap", "title"=>"DNS-Server und Gateways",),
                                    "90"=>array("name"=>"Keys", "link"=>"./list.php?view=statistic_keys", "image"=>"fa-key", "title"=>"Lizenzschlüssel",),
                                    "92"=>array("name"=>"Model", "link"=>"list.php?view=statistic_model", "image"=>"fa-laptop", "title"=>"Modelle",), 
                                    "94"=>array("name"=>"Manufacturer", "link"=>"list.php?view=statistic_manufacturer", "image"=>"fa-truck", "title"=>"Hersteller",), 
                              ),
              ),
      "30" => array("name"=>"Discovered Ports","image"=>"fa-universal-access",
                    "link"=>"list.php?view=all_nmap_ports",
                    "class"=>"menuparent",
                    "childs"=>array("10"=>array("name"=>"All Active Ports", "link"=>"./list.php?view=all_nmap_ports", "image"=>"fa-sign-in", "title"=>"Active ports discovered by NMAP scan",),
                                    "20"=>array("name"=>"All Active Ports with hosts", "link"=>"./list.php?view=nmap_ports_hosts", "image"=>"fa-sign-in", "title"=>"Active ports discovered by NMAP scan with hosts",),
                                    "30"=>array("name"=>"Active Ports on Systems", "link"=>"./list.php?view=all_nmap_ports_systems", "image"=>"fa-sign-in", "title"=>"Active ports discovered by NMAP scan on systems",),
                                    "40"=>array("name"=>"Active Ports with Systems", "link"=>"./list.php?view=nmap_ports_systems", "image"=>"fa-sign-in", "title"=>"Active ports discovered by NMAP scan with systems",),
                                    "50"=>array("name"=>"Active Ports on Other Hosts", "link"=>"./list.php?view=all_nmap_ports_other", "image"=>"fa-sign-in", "title"=>"Active ports discovered by NMAP scan on other systems",),
                                    "60"=>array("name"=>"Active Ports with Other Hosts", "link"=>"./list.php?view=nmap_ports_other", "image"=>"fa-sign-in", "title"=>"Active ports discovered by NMAP scan with other systems",),

                             ),
              ),
      "40" => array("name"=>"Software Register","image"=>"fa-legal",
                    "link"=>"./list.php?view=software_register",
                    "class"=>"menuparent",
                    "childs"=>array("10"=>array("name"=>"Software Register", "link"=>"./list.php?view=software_register", "image"=>"fa-legal", "title"=>"",),
                                    "20"=>array("name"=>"Add Software", "link"=>"./software_register_add.php", "image"=>"fa-plus-square", "title"=>"",),
									"22"=>array("name"=>"Add Licenses", "link"=>"./software_register.php", "image"=>"fa-plus-circle", "title"=>"",),
                                    "30"=>array("name"=>"Delete Software", "link"=>"./software_register_del.php", "image"=>"fa-window-close-o", "title"=>"",),
                              ),
              ),
      "60" => array("name"=>"Admin", "image"=>"fa-cog",
                    "link"=>"import_svversion.php",
                    "class"=>"menuparent",
                    "childs"=>array(
                    				"8"=>array("name"=>"IP-Liste erzeugen", "link"=>"export-ipliste-4-openaudit.php", "image"=>"fa-plus", "title"=>"pc_list_file_text aus Netzwerkliste erstellen",),
									"10"=>array("name"=>"Import SVVersionen", "link"=>"import_svversion.php", "image"=>"fa-download", "title"=>"Softwareversions and license Database import",),
                    				"12"=>array("name"=>"Select Database", "link"=>"changedatabase.php", "image"=>"fa-database", "title"=>"Select what database of installed dbs to use",),
									"14"=>array("name"=>"Delete/Create new database", "link"=>"./setup.php", "image"=>"fa-times-circle", "title"=>"",),
                    				"20"=>array("name"=>"Config", "link"=>"admin_config.php?sub=1", "image"=>"fa-gear", "title"=>"",),
                                    "30"=>array("name"=>"Add a System", "link"=>"admin_pc_add_1.php?sub=1", "image"=>"fa-plus-square", "title"=>"",),
                                    "31"=>array("name"=>"Add NMAP-Scanned", "link"=>"admin_nmap_input.php?sub=1", "image"=>"fa-plus-circle", "title"=>"",),
                                    "40"=>array("name"=>"Delete Systems", "link"=>"./delete_systems.php", "image"=>"fa-minus-square", "title"=>"",),
                                    "45"=>array("name"=>"Delete Systems older " . $days_systems_not_audited ." days", "link"=>"./delete_missed_audits.php", "image"=>"fa-minus-circle", "title"=>"",),
                                    "50"=>array("name"=>"Delete Other Items", "link"=>"./delete_other_systems.php", "image"=>"fa-minus-square-o", "title"=>"",),
                                    "60"=>array("name"=>"Audit My Machine", "link"=>"launch_local_audit.php", "image"=>"fa-eye", "title"=>"Download and Run the Audit Script from your machine.",),
                                    "70"=>array("name"=>"Backup Database", "link"=>"database_backup_form.php", "image"=>"fa-copy", "title"=>"",),
                                    "80"=>array("name"=>"Restore Database", "link"=>"database_restore_form.php", "image"=>"fa-support", "title"=>"",),
                                    "90"=>array("name"=>"View Event Log", "link"=>"./list.php?view=event_log", "image"=>"fa-file-text-o", "title"=>"",),
                            ),
              ),

      "63" => array("name"=>"CSV2XLSX", "image"=>"fa-recycle",
                    "link"=>"/openaudit/csvxls.php",
                    "class"=>"menuparent",
                    "title"=>"CSV-Dateien in Excel konvertieren (Batch)",
              ),

      "65" => array("name"=>"PHPMyAdmin", "image"=>"fa-database",
                    "link"=>"/phpmyadmin",
                    "class"=>"menuparent",
                    "title"=>"Mysql Admin-Oberfläche aufrufen",
              ),

      "68" => array("name"=>"Wordpress-BLOG", "image"=>"fa-wordpress",
                    "link"=>"/wordpress",
                    "class"=>"menuparent",
                    "title"=>"Wordpress-Instanz als Intranet nutzen",
              ),

      "70" => array("name"=>"Help", "image"=>"fa-question-circle",
                    "link"=>"./show_tips.php",
                    "class"=>"menuparent",
                    "title"=>"Hilfe und Lizenzvertrag",
                    "childs"=>array("60"=>array("name"=>"Help Tips&Tricks", "link"=>"./show_tips.php", "image"=>"fa-file-text-o", "title"=>"Tipps und Tricks anzeigen",),
                                    "50"=>array("name"=>"GPL License Display", "link"=>"./show_license.php", "image"=>"fa-legal", "title"=>"GPL license text",),
                             ),       
              ),
  ),
);

// Add in the following entry for Auditing the LDAP if necessary.
if ((isset($use_ldap_integration))and($use_ldap_integration == 'y')) {
 $menue_array['misc']['60']['childs']['100']=array("name"=>"Audit LDAP Directory", "link"=>"ldap_audit_script.php", "image"=>"fa-phone", "title"=>"Audit the LDAP Directory.",);
};
if ((isset($show_dell_warranty ))and($show_dell_warranty  == 'y')) {
 $menue_array['misc']['10']['childs']['230']=array("name"=>"All Dell Warranty", "link"=>"./list.php?view=all_dell_warranty", "image"=>"fa-dollar", "title"=>"All Dell Warranty.",);
};


?>
