<?php

$query_array=array("headline"=>__("List all Network Equipment"),
                   "sql"=>"SELECT * FROM other WHERE (other_ip_address <> '' AND other_ip_address <> ' Not-Networked') ",
                   "sort"=>"other_ip_address",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("other"=>"%other_id",
                                             "view"=>"other_system",
                                            ),
                               ),
                   "fields"=>array(
                                   "8"=>array("name"=>"other_ip_address",
                                               "head"=>__("IP Address"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "10"=>array("name"=>"other_network_name",
                                               "head"=>__("Network Name"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "16"=>array("name"=>"other_manufacturer",
                                               "head"=>__("Manufacturer"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "20"=>array("name"=>"other_description",
                                               "head"=>__("Description"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "23"=>array("name"=>"other_location",
                                               "head"=>__("Ort-Details"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"other_type",
                                               "head"=>__("Type"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"other_mac_address",
                                               "head"=>__("MAC Address"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "62"=>array("name"=>"other_first_timestamp",
                                               "head"=>__("First-audit"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                  ),
                  );
?>
