<?php
    if (!empty($_GET["headline_addition"])) $filtered = 'AND net.net_gateway = \'' . $_GET["headline_addition"].'\''; else $filtered='';
	$query_array=array("headline"=>__("List Systems with Gateway"),
                       "sql"=>"SELECT DISTINCT sys.system_uuid, sys.net_ip_address, sys.system_name, net.net_gateway, net.net_dns_server, net.net_dns_server_2, sys.net_domain,
                                      sys.system_os_name, sys.system_service_pack, sys.system_timestamp, sys.system_system_type, sys.system_description
                               FROM system sys, network_card net
                               WHERE net.net_uuid  = sys.system_uuid
                               AND sys.system_timestamp  = net.net_timestamp ".$filtered." 
                               AND (net.net_ip_address != 'none' OR net.net_ip_address_2 != 'none' OR net.net_ip_address_3 != 'none') ",
                       "sort"=>"sys.system_name",
                       "dir"=>"ASC",
                       "get"=>array("file"=>"system.php",
                                    "title"=>"Go to System",
                                    "var"=>array("pc"=>"%system_uuid",
                                                 "view"=>"summary",
                                                ),
                                   ),
                       "fields"=>array("10"=>array("name"=>"sys.system_uuid",
                                                   "head"=>__("UUID"),
                                                   "show"=>"n",
                                                  ),
                                       "20"=>array("name"=>"sys.net_ip_address",
                                                   "head"=>__("IP"),
                                                   "show"=>"y",
                                                   "link"=>"y",
                                                  ),
                                       "30"=>array("name"=>"sys.system_name",
                                                   "head"=>__("Hostname"),
                                                   "show"=>"y",
                                                   "link"=>"y",
                                                  ),
                                       "40"=>array("name"=>"net.net_gateway",
                                                   "head"=>__("Gateway"),
                                                   "show"=>"y",
                                                   "link"=>"n",
                                                  ),
                                       "41"=>array("name"=>"net.net_dns_server",
                                                   "head"=>__("DNS1"),
                                                   "show"=>"y",
                                                   "link"=>"n",
                                                  ),
                                       "42"=>array("name"=>"net.net_dns_server_2",
                                                   "head"=>__("DNS2"),
                                                   "show"=>"y",
                                                   "link"=>"n",
                                                  ),
                                        "50"=>array("name"=>"sys.net_domain",
                                                   "head"=>__("Domain"),
                                                   "show"=>$show_domain,
                                                  ),
                                       "60"=>array("name"=>"sys.system_os_name",
                                                   "head"=>__("OS"),
                                                   "show"=>$show_os,
                                                  ),
                                       "70"=>array("name"=>"sys.system_service_pack",
                                                   "head"=>__("Servicepack"),
                                                   "show"=>$show_service_pack,
                                                  ),
                                       "80"=>array("name"=>"sys.system_timestamp",
                                                   "head"=>__("Date Audited"),
                                                   "show"=>$show_date_audited,
                                                  ),
                                       "90"=>array("name"=>"sys.system_system_type",
                                                   "head"=>__("System Type"),
                                                   "show"=>$show_type,
                                                   "align"=>"center",
                                                  ),
                                       "100"=>array("name"=>"sys.system_description",
                                                   "head"=>__("Description"),
                                                   "show"=>$show_description,
                                                  ),
                                      ),
                      );
?>