<?php

$query_array=array("headline"=>__("List all Scheduled Tasks with Hosts"),
                   "sql"=>"SELECT * FROM scheduled_task, system WHERE sched_task_uuid = system_uuid  AND sched_task_timestamp = system_timestamp ",
                   "sort"=>"sched_task_name, system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("pc"=>"%sched_task_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"sched_task_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"sched_task_name",
                                               "head"=>__("Task Name"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "get"=>array("file"=>"system.php",
                                                            "title"=>__("Go to System"),
                                                            "var"=>array("pc"=>"%system_uuid",
                                                                         "view"=>"os",
                                                                        ),
                                                           ),
                                              ),
                                   "40"=>array("name"=>"sched_task_next_run",
                                               "head"=>__("Next Run"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "50"=>array("name"=>"sched_task_last_result",
                                               "head"=>__("Last Run Status"),
                                               "show"=>"n",
                                               "link"=>"n",
                                              ), 
                                   "60"=>array("name"=>"sched_task_last_run",
                                               "head"=>__("Last Run"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "70"=>array("name"=>"sched_task_schedule",
                                               "head"=>__("Schedule"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "80"=>array("name"=>"sched_task_state",
                                               "head"=>__("Task State"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "90"=>array("name"=>"sched_task_task",
                                               "head"=>__("Path"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "100"=>array("name"=>"sched_task_runas",
                                               "head"=>__("Run As"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "110"=>array("name"=>"sched_task_creator",
                                               "head"=>__("Creator"),
                                               "show"=>"n",
                                               "link"=>"n",
                                              ), 
                                  ),
                  );
?>