<?php

// (system_system_type = 'Other' OR system_system_type = 'Unknown' OR system_system_type = 'Desktop' OR system_system_type = 'Low Profile Desktop' OR system_system_type = 'Pizza Box' OR system_system_type = 'Mini Tower' OR system_system_type = 'Tower' OR system_system_type = 'All in One' OR system_system_type = 'Space-Saving' OR system_system_type = 'Lunch Box' OR system_system_type = 'Sealed-Case PC'
//						 OR system_system_type = 'Embedded PC' OR system_system_type = 'Mini PC' OR system_system_type = 'Stick PC' )

$query_array=array("headline"=>__("List all Systems with TPM Chip"),
                   "sql"=>"SELECT * FROM `system`, `processor` WHERE system_tpmver<>'' 
					AND system_timestamp = processor_timestamp 
				    AND processor_device_id = 'CPU0' ",
                   "sort"=>"system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"net_ip_address",
                                               "head"=>__("IP"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                  "32"=>array("name"=>"system_os_name",
                                               "head"=>__("OS"),
                                               "show"=>$show_os,
                                              ),
                                  "34"=>array("name"=>"system_version",
                                               "head"=>__("OS-Version"),
                                               "show"=>"y",
                                              ),
                                   "45"=>array("name"=>"system_system_type",
                                               "head"=>__("System Type"),
                                               "show"=>$show_type,
                                               "align"=>"left",
                                              ),
                                   "48"=>array("name"=>"processor_name",
                                               "head"=>__("CPU"),
                                               "show"=>"y",
                                              ),
                                   "49"=>array("name"=>"system_num_processors",
                                               "head"=>__("# cpu"),
                                               "show"=>"y",
                                              ),
                                   "50"=>array("name"=>"system_tpmver",
                                               "head"=>__("TPM Ver"),
                                               "show"=>"y",
                                              ),
                                   "51"=>array("name"=>"tpm_init",
                                               "head"=>__("TPM aktiv"),
                                               "show"=>"y",
                                              ),
                                   "52"=>array("name"=>"tpm_password",
                                               "head"=>__("TPM PWD"),
                                               "show"=>"y",
                                              ),

                                   "54"=>array("name"=>"system_vendor",
                                               "head"=>__("Vendor"),
                                               "show"=>"y",
                                              ), 
                                   "55"=>array("name"=>"system_model",
                                               "head"=>__("Model"),
                                               "show"=>"y",
                                              ),           
								   "100"=>array("name"=>"system_os_arch",
                                               "head"=>__("OS Arch."),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),		  
                                   "142"=>array("name"=>"system_description",
                                               "head"=>__("Description"),
                                               "show"=>$show_description,
                                              ),
                                   "143"=>array("name"=>"net_domain_role",
                                               "head"=>__("DCMember"),
                                               "show"=>"y",
                                              ),           
                                    "144"=>array("name"=>"net_domain",
                                               "head"=>__("Domain"),
                                               "show"=>$show_domain,
                                              ),
                                   "155"=>array("name"=>"net_user_name",
                                               "head"=>__("Username"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "160"=>array("name"=>"system_id_number",
                                               "head"=>__("Serial #"),
                                               "show"=>"y",
                                              ),
                                   "165"=>array("name"=>"system_language",
                                               "head"=>__("Sprache"),
                                               "show"=>"y",
                                              ),
								  "170"=>array("name"=>"system_timestamp",
                                               "head"=>__("Date Audited"),
                                               "show"=>$show_date_audited,
                                              ),
                                  ),
                  );
?>
