<?php
$query_array=array("headline"=>__("List all Systems Manual Fields"),
                   "sql"=>"SELECT system.system_uuid , system.system_name, system.net_user_name, system.system_vendor, system.system_model, system.system_description, system_man.system_man_uuid, system_man.system_man_location, system_man.system_man_date_of_purchase, system_man.system_man_value,  system_man.system_man_serial_number, system_man.system_man_description FROM system LEFT JOIN `system_man` ON system.system_uuid = system_man.system_man_uuid",
				   "sort"=>"system_name",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Go to System"),
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"summary",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "40"=>array("name"=>"net_user_name",
                                               "head"=>__("Username"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "50"=>array("name"=>"system_vendor",
                                               "head"=>__("Vendor"),
                                               "show"=>"y",
                                              ), 
                                   "60"=>array("name"=>"system_model",
                                               "head"=>__("Model"),
                                               "show"=>"y",
                                              ),           
                                   "70"=>array("name"=>"system_description",
                                               "head"=>__("Description"),
                                               "show"=>$show_description,
                                              ),
									"80"=>array("name"=>"system_man_description",
                                               "head"=>__("Manual description"),
                                               "show"=>"y",
                                              ),	
									"90"=>array("name"=>"system_man_location",
                                               "head"=>__("Manual Location"),
                                               "show"=>"y",
                                              ),
  									"100"=>array("name"=>"system_man_date_of_purchase",
                                               "head"=>__("Manual Purchase date"),
                                               "show"=>"y",
                                              ),
  									"110"=>array("name"=>"system_man_serial_number",
                                               "head"=>__("Manual Asset Tag"),
                                               "show"=>"y",
                                              ),										  
  									"120"=>array("name"=>"system_man_value",
                                               "head"=>__("Manual fiscal value"),
                                               "show"=>"y",
                                              ),											  
                                  ),
                  );
?>
