<?php

$query_array=array("headline"=>array("name"=>__("Startup-Software"),
                                     "sql"=>"SELECT `system_name` FROM `system` WHERE `system_uuid` = '" . $_REQUEST["pc"] . "'",
                                     ),
                   "sql"=>"SELECT * FROM startup WHERE startup_uuid = '".$_REQUEST["pc"]."' AND startup_timestamp = '".$GLOBALS["timestamp"]."' ",
                   "sort"=>"startup_caption",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"list.php",
                                "title"=>__("Hosts with this Startup-Software"),
                                "var"=>array("view"=>"systems_for_startupsoftware",
                                             "name"=>"%startup_caption",
                                             "headline_addition"=>"%startup_caption",
                                            ),
                               ),
                   "fields"=>array("10"=>array("name"=>"startup_caption",
                                               "head"=>__("Name"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                   "20"=>array("name"=>"startup_user",
                                               "head"=>__("User"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"startup_location",
                                               "head"=>__("Location"),
                                               "show"=>"y",
                                               "link"=>"n",
                                               "help"=>"%startup_command",
                                              ),

                                   "40"=>array("name"=>"startup_command",
                                               "head"=>__("Executable"),
                                               "show"=>"y",
                                               "link"=>"y",
                                               "search"=>"n",
                                               "sort"=>"n",
                                               "image"=>"images/software.png",
                                               "help"=>"%startup_command",
                                              ),
                                  ),
                  );
?>
