<?php
// This is a viewdef from Open Audit 
$query_array=array("headline"=>__("List Anti Virus Information"),
                   "sql"=>"SELECT * FROM `system`",
                   "sort"=>"virus_uptodate",
                   "dir"=>"ASC",
                   "get"=>array("file"=>"system.php",
                                "title"=>__("Anti Virus Status"),
                                "var"=>array("pc"=>"%system_uuid",
                                             "view"=>"security",
                                            ),
                               ),
                               // More comments
                   "fields"=>array("10"=>array("name"=>"system_uuid",
                                               "head"=>__("UUID"),
                                               "show"=>"n",
                                              ),
                                   "20"=>array("name"=>"system_os_name",
                                               "head"=>__("System OS Name"),
                                               "show"=>"n",
                                               "link"=>"n",
                                              ),
                                   "30"=>array("name"=>"system_name",
                                               "head"=>__("Hostname"),
                                               "show"=>"y",
                                               "link"=>"y",
                                              ),
                                    "40"=>array("name"=>"net_user_name",
                                               "head"=>__("Network User"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                    "50"=>array("name"=>"virus_manufacturer",
                                               "head"=>__("Firewall Vendor"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                    "52"=>array("name"=>"firewall_enabled_domain",
                                               "head"=>__("FW Domain on"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                    "54"=>array("name"=>"firewall_enabled_standard",
                                               "head"=>__("FW public on"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                    "60"=>array("name"=>"virus_name",
                                               "head"=>__("Anti Virus Software Name"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                    "70"=>array("name"=>"virus_version",
                                               "head"=>__("AV Last update"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                    "73"=>array("name"=>"virus_date",
                                               "head"=>__("AV Date"),
                                               "show"=>"n",
                                               "link"=>"n",
                                              ),
                                    "80"=>array("name"=>"virus_uptodate",
                                               "head"=>__("Anti Virus Up To Date"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),
                                    "90"=>array("name"=>"system_timestamp",
                                               "head"=>__("Last Audited"),
                                               "show"=>"y",
                                               "link"=>"n",
                                              ),

                                  ),
                  );
?>