<?php
    $query_array=array("name"=>array("name"=>__("Security"),
                                     "sql"=>"SELECT `system_name` FROM `system` WHERE `system_uuid` = '" . $_GET["pc"] . "'",
                                    ),
                       "views"=>array("win_firewall"=>array(
                                                        "headline"=>__("Windows Firewall"),
                                                        "sql"=>"SELECT * FROM system WHERE system_uuid = '" . $_GET["pc"] . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."' ",
                                                        "image"=>"./images/firewall_l.png",
                                                        "fields"=>array("10"=>array("name"=>"firewall_enabled_domain", "head"=>__("Domain - Firewall Enabled"),),
                                                                        "20"=>array("name"=>"firewall_disablenotifications_domain", "head"=>__("Domain - Notifications to User"),),
                                                                        "30"=>array("name"=>"firewall_donotallowexceptions_domain", "head"=>__("Domain - Exceptions Allowed"),),
                                                                        "40"=>array("name"=>"firewall_enabled_standard", "head"=>__("Standard - Firewall Enabled"),),
                                                                        "50"=>array("name"=>"firewall_disablenotifications_standard", "head"=>__("Standard - Notifications to User"),),
                                                                        "60"=>array("name"=>"firewall_donotallowexceptions_standard", "head"=>__("Standard - Exceptions Allowed"),),
                                                                        "70"=>array("name"=>"", "head"=>__(""),),
                                                                        "80"=>array("head"=>__("Port Exceptions"),
                                                                                    "get"=>array("head"=>__("Click me!"),
                                                                                                 "file"=>"list.php",
                                                                                                 "title"=>__("Click me!"),
                                                                                                 "var"=>array("pc"=>"%system_uuid",
                                                                                                              "view"=>"port_exceptions_for_system",
                                                                                                              "headline_addition"=>"%system_name",
                                                                                                             ),
                                                                                                ),
                                                                                    ),
                                                                        "90"=>array("head"=>__("Program Exceptions"),
                                                                                    "get"=>array("head"=>__("Click me!"),
                                                                                                 "file"=>"list.php",
                                                                                                 "title"=>__("Click me!"),
                                                                                                 "var"=>array("pc"=>"%system_uuid",
                                                                                                              "view"=>"program_exceptions_for_system",
                                                                                                              "headline_addition"=>"%system_name",
                                                                                                             ),
                                                                                                ),
                                                                                    ),
                                                                       ),
                                                        ),
                                       "firewall_other"=>array(
                                                        "headline"=>__("Other Firewalls"),
                                                        "sql"=>"SELECT * from software WHERE software_uuid = '" . $_GET["pc"] . "' AND software_timestamp = '".$GLOBAL["system_timestamp"]."'
                                                                                             AND (software_name LIKE '%ZoneAlarm%'
                                                                                                  OR software_name LIKE '%Internet Security%'
                                                                                                  OR software_name LIKE '%Firewall%')",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/firewall_l.png",
                                                        "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                       ),
                                                        ),
                                       "antivirus_xp"=>array(
                                                        "headline"=>__("Windows Security Center Registered Antivirus"),
                                                        "sql"=>"SELECT * from system WHERE system_uuid = '" . $_GET["pc"] . "' AND system_timestamp = '".$GLOBAL["system_timestamp"]."'  AND (virus_name <> '' OR virus_manufacturer <> '') ",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/antivirus_l.png",
                                                        "fields"=>array("10"=>array("name"=>"virus_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"virus_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"virus_manufacturer", "head"=>__("Manufacturer"),),
                                                                        "40"=>array("name"=>"virus_uptodate", "head"=>__("Up-to-date"),),
                                                                       ),
                                                        ),
                                       "antivirus_other"=>array(
                                                        "headline"=>__("Other Antivirus"),
                                                        "sql"=>"SELECT * from software WHERE software_uuid = '" . $_GET["pc"] . "' AND software_timestamp = '".$GLOBAL["system_timestamp"]."'
                                                                                             AND (software_name LIKE '%Avast%'
                                                                                                  OR software_name LIKE '%Antivir%'
                                                                                                  OR software_name LIKE '%Internet Security%'
                                                                                                  OR software_name LIKE '%Virus%'
                                                                                                  OR software_name LIKE '%Client Security%')",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/firewall_l.png",
                                                        "fields"=>array("10"=>array("name"=>"software_name", "head"=>__("Name"),),
                                                                        "20"=>array("name"=>"software_version", "head"=>__("Version"),),
                                                                        "30"=>array("name"=>"software_publisher", "head"=>__("Publisher"),),
                                                                       ),
                                                        ),
                                       "auto_updating"=>array(
                                                        "headline"=>__("Automatic Updating Client Settings"),
                                                        "sql"=>"SELECT * from auto_updating WHERE au_uuid = '" . $_GET["pc"] . "' AND au_timestamp = '".$GLOBAL["system_timestamp"]."'",
                                                        "image"=>"./images/scsi_l.png",
                                                        "fields"=>array("10"=> array("name"=>"au_gpo_configured", "head"=>__("AU Client is configured by a GPO"),),
                                                                        "20"=> array("name"=>"au_enabled", "head"=>__("AU Client is enabled"),),
                                                                        "30"=> array("name"=>"au_behaviour", "head"=>__("AU Client behaviour"),),
                                                                        "40"=> array("name"=>"au_sched_install_day", "head"=>__("Scheduled install day"),),
                                                                        "50"=> array("name"=>"au_sched_install_time", "head"=>__("Scheduled install time"),),
                                                                        "60"=> array("name"=>"au_use_wuserver", "head"=>__("Use a WSUS server"),),
                                                                        "70"=> array("name"=>"au_wuserver", "head"=>__("WSUS server"),),
                                                                        "80"=> array("name"=>"au_wustatusserver", "head"=>__("WSUS Status server"),),
                                                                        "90"=> array("name"=>"au_target_group", "head"=>__("WSUS Target Group"),),
                                                                        "100"=>array("name"=>"au_elevate_nonadmins", "head"=>__("Allow non-admins to receive update notifications"),),
                                                                        "110"=>array("name"=>"au_auto_install", "head"=>__("Automatic installation of minor updates"),),
                                                                        "120"=>array("name"=>"au_detection_frequency", "head"=>__("Automatic updates detection frequency (hours)"),),
                                                                        "130"=>array("name"=>"au_reboot_timeout", "head"=>__("Delay before prompting again for restart (minutes)"),),
                                                                        "140"=>array("name"=>"au_noautoreboot", "head"=>__("No auto-restart for scheduled installations"),),
                                                                       ),
                                                        ),
                                       "nmap"=>array(
                                                        "headline"=>__("Open Ports discovered by Nmap"),
                                                        "sql"=>"SELECT * from nmap_ports WHERE nmap_other_id = '" . $_REQUEST["pc"] . "' ORDER BY nmap_port_number",
                                                        "table_layout"=>"horizontal",
                                                        "image"=>"./images/nmap_l.png",
                                                        "fields"=>array("10"=>array("name"=>"nmap_port_number", "head"=>__("Port"),),
                                                                        "20"=>array("name"=>"nmap_port_proto", "head"=>__("Protocol"),),
                                                                        "30"=>array("name"=>"nmap_port_name", "head"=>__("Service"),),
                                                                        "40"=>array("name"=>"nmap_port_version", "head"=>__("Version"),),
                                                                       ),
                                                        ),

                                     ),
                      );
?>
